### ISSUE TITLE
[RestoLaksmackt][Restoration Druid] OOC Healing not working

### ISSUE THREAD

**Issue by dgepic** [CuteOne/BadRotations#1007]
Which Unlocker are you using?

EWT

Do you have BugGrabber and BugSack Installed?

No

If Yes, please post the error below

Which Class / Spec / Rotation Were you using during the bug.

Restoration Druid

After a /reload were you able to reproduce the error?

Yes

Please give any other relevant information regarding the bug (Only happens in raid, open world, etc.)

Out-Of-Combat Healing does not work for RestoLaksmackt. I switched to RestoAura and it works on that profile but not when I switch back. Healing will not start until I 'enter combat'. Other non-combat actions do work; for example changing into a cat for movement.

**Comment by Laksmack** [comment]
Just tested this - it works if you select OOC HEALING in the settings, otherwise it does not.  If you want clarification or to discuss - hit me up in #druid on BR discord
