### ISSUE TITLE
beast master

### ISSUE THREAD

**Issue by itzjaayman** [CuteOne/BadRotations#102]
Kill command is now barely triggering since I updated to the new rotation along with a lot of other spells not triggering or only doing so periodically.
I have tried simc amr and Kuku but all seem to have similar problems my current average dps wit the current update is only around 200k
 When i rolled back to a previous version(the version where the fix to stampede had just applied) my DPS was around the 780k mark
Checking my dps logs on the newest version available it showed kill command and dire beast almost never triggered

This rotation was almost perfect can someone please fix this asap

**Comment by itzjaayman** [comment]
no longer any issues everything seems fine and working again

**Comment by kuukuukuatchu** [comment]
Closingas issue resolved
