### ISSUE TITLE
Druid balance & DH havoc freeze

### ISSUE THREAD

**Issue by manessa** [CuteOne/BadRotations#104]
Hi, first i'd like to thanks CuteOne and LyLoLoq for this great addon & rotation!
When i play my druid restoration everything is fine but when i play the balance specialization i often have to reload the ui because it 'freeze' the game (fps go down to 1 and i have to stop the rotation or the game is frozen :D) when i start the rotation.
Many times it's after i change area, here my 'errors' messages, i hope it can help you to fixe it. 📄 
[tmp.txt](https://github.com/CuteOne/BadRotations/files/866135/tmp.txt)

...AddOns\BadRotations\System\Engines\EnemiesEngine.lua:49: script ran too long
Count: 2

Call Stack:
[C]: in function `UnitExists'
...AddOns\BadRotations\System\Engines\EnemiesEngine.lua:49: in function <...AddOns\BadRotations\System\Engines\EnemiesEngine.lua:48>
...AddOns\BadRotations\System\Engines\EnemiesEngine.lua:146: in function `EnemiesEngine'
Interface\AddOns\BadRotations\System\Core.lua:235: in function <Interface\AddOns\BadRotations\System\Core.lua:124>

...face\AddOns\BadRotations\System\Engines\ttdTable.lua:31: script ran too long
Count: 1

Call Stack:
[C]: in function `UnitHealth'
...face\AddOns\BadRotations\System\Engines\ttdTable.lua:31: in function `TTDRefresh'
...face\AddOns\BadRotations\System\Engines\ttdTable.lua:61: in function `getTTD'
...Rotations\Rotations\Druid\Balance\BalanceLyLoLoq.lua:859: in function `actionList_Combat'
...Rotations\Rotations\Druid\Balance\BalanceLyLoLoq.lua:1348: in function `run'
...terface\AddOns\BadRotations\Rotations\cCharacter.lua:295: in function `startRotation'
Interface\AddOns\BadRotations\Rotations\cBuilder.lua:381: in function `update'
Interface\AddOns\BadRotations\System\Core.lua:164: in function <Interface\AddOns\BadRotations\System\Core.lua:124>

**Comment by Druxlolz** [comment]
Hello i have been experiencing this as well so not a problem on his end :) gl

**Comment by LyLoLoq** [comment]
Hello, im working on a fix to that

**Comment by manessa** [comment]
more errors for the same problem, this time with the demon hunter havoc 

...ations\Rotations\Demon Hunter\Havoc\HavocCuteOne.lua:272: attempt to call global 'SetCurrentSpeed' (a nil value)
Count: 30

Call Stack:
[C]: in function `SetCurrentSpeed'
...ations\Rotations\Demon Hunter\Havoc\HavocCuteOne.lua:272: in function <...ations\Rotations\Demon Hunter\Havoc\HavocCuteOne.lua:272>


...face\AddOns\BadRotations\System\Engines\ttdTable.lua:50: script ran too long
Count: 1

Call Stack:
[C]: in function `UnitExists'
...face\AddOns\BadRotations\System\Engines\ttdTable.lua:50: in function `TTDRefresh'
...face\AddOns\BadRotations\System\Engines\ttdTable.lua:61: in function <...face\AddOns\BadRotations\System\Engines\ttdTable.lua:60>
...ations\Rotations\Demon Hunter\Havoc\HavocCuteOne.lua:393: in function `actionList_Cooldowns'
...ations\Rotations\Demon Hunter\Havoc\HavocCuteOne.lua:510: in function `run'
...terface\AddOns\BadRotations\Rotations\cCharacter.lua:295: in function `startRotation'
Interface\AddOns\BadRotations\Rotations\cBuilder.lua:381: in function `update'
Interface\AddOns\BadRotations\System\Core.lua:164: in function <Interface\AddOns\BadRotations\System\Core.lua:124>

**Comment by LyLoLoq** [comment]
is this still happening after last update of FH and BR?

**Comment by manessa** [comment]
Hello Lyloloq, i was following the updates and unfortunately it's not fixed.
I have to reload so often my 'ui', i feel like i have to create my rotation (old pqr creator) but thanks for your efforts and support! 📦 
For me it's the ennemy engine that freeze.

**Comment by LyLoLoq** [comment]
can u send me log of the error plz?

**Comment by manessa** [comment]
No saved but it was EnemiesEngine.lua script ran too long, after 2 reload ui i had no error & it worked again.

**Comment by manessa** [comment]
Healing profile without attack is much more stable here.

**Comment by LyLoLoq** [comment]
are u on discord? send me a private there plz

**Comment by manessa** [comment]
Yes but i can't find your id and email dont work. :p

**Comment by manessa** [comment]
...face\AddOns\BadRotations\System\Engines\ttdTable.lua:50: script ran too long
Count: 2

Call Stack:
[C]: in function `UnitExists'
...face\AddOns\BadRotations\System\Engines\ttdTable.lua:50: in function `TTDRefresh'
...face\AddOns\BadRotations\System\Engines\ttdTable.lua:61: in function `getTTD'
...Rotations\Rotations\Druid\Balance\BalanceLyLoLoq.lua:878: in function `actionList_Combat'
...Rotations\Rotations\Druid\Balance\BalanceLyLoLoq.lua:1490: in function `run'
...terface\AddOns\BadRotations\Rotations\cCharacter.lua:295: in function `startRotation'
Interface\AddOns\BadRotations\Rotations\cBuilder.lua:381: in function `update'
Interface\AddOns\BadRotations\System\Core.lua:177: in function <Interface\AddOns\BadRotations\System\Core.lua:137>

**Comment by manessa** [comment]
...face\AddOns\BadRotations\System\Engines\ttdTable.lua:50: script ran too long
Count: 1

Call Stack:
[C]: in function `UnitExists'
...face\AddOns\BadRotations\System\Engines\ttdTable.lua:50: in function `TTDRefresh'
...face\AddOns\BadRotations\System\Engines\ttdTable.lua:61: in function `getTTD'
...Rotations\Rotations\Druid\Balance\BalanceLyLoLoq.lua:884: in function `actionList_Combat'
...Rotations\Rotations\Druid\Balance\BalanceLyLoLoq.lua:1490: in function `run'
...terface\AddOns\BadRotations\Rotations\cCharacter.lua:295: in function `startRotation'
Interface\AddOns\BadRotations\Rotations\cBuilder.lua:381: in function `update'
Interface\AddOns\BadRotations\System\Core.lua:177: in function <Interface\AddOns\BadRotations\System\Core.lua:137>

**Comment by LyLoLoq** [comment]
just made a commit, cand u see if its better?

**Comment by manessa** [comment]
Sure, thanks for your efforts i will try now!

**Comment by manessa** [comment]
I have played druid resto & dps, switching instances & spec many times and got this with the balance.

...s\BadRotations\System\UI\Toggles\ToggleFunctions.lua:259: attempt to index field '?' (a nil value)
Count: 11

Call Stack:
[C]: ?
...s\BadRotations\System\UI\Toggles\ToggleFunctions.lua:259: in function <...s\BadRotations\System\UI\Toggles\ToggleFunctions.lua:257>



and


...face\AddOns\BadRotations\System\GeneralFunctions.lua:11: script ran too long
Count: 2

Call Stack:
[C]: in function `UnitExists'
...face\AddOns\BadRotations\System\GeneralFunctions.lua:11: in function `GetUnitExists'
...AddOns\BadRotations\System\Engines\EnemiesEngine.lua:49: in function <...AddOns\BadRotations\System\Engines\EnemiesEngine.lua:48>
...AddOns\BadRotations\System\Engines\EnemiesEngine.lua:146: in function `EnemiesEngine'
Interface\AddOns\BadRotations\System\Core.lua:248: in function <Interface\AddOns\BadRotations\System\Core.lua:137>

**Comment by LyLoLoq** [comment]
thx for the report! i will try something new now

**Comment by manessa** [comment]
Got a new one but no freeze this time lol.

Interface\AddOns\!BaudErrorFrame\BaudErrorFrame.lua:56: attempt to concatenate global 'arg1' (a nil value)
Count: 10

Call Stack:
[C]: ?
Interface\AddOns\!BaudErrorFrame\BaudErrorFrame.lua:56: in function `?'
Interface\AddOns\!BaudErrorFrame\BaudErrorFrame.lua:92: in function <Interface\AddOns\!BaudErrorFrame\BaudErrorFrame.lua:91>
[C]: in function `Hide'
...s\BadRotations\System\UI\Toggles\ToggleFunctions.lua:12: in function `GarbageButtons'
Interface\AddOns\BadRotations\Rotations\cBuilder.lua:548: in function `createToggles'
Interface\AddOns\BadRotations\System\Core.lua:172: in function <Interface\AddOns\BadRotations\System\Core.lua:137>

**Comment by LyLoLoq** [comment]
i think the previous error got solved

**Comment by manessa** [comment]
Still freezing ...face\AddOns\BadRotations\System\GeneralFunctions.lua:14: script ran too long
Count: 2

Call Stack:
[C]: in function `UnitExists'
...face\AddOns\BadRotations\System\GeneralFunctions.lua:14: in function `GetUnitExists'
...face\AddOns\BadRotations\System\Engines\ttdTable.lua:50: in function `TTDRefresh'
...face\AddOns\BadRotations\System\Engines\ttdTable.lua:61: in function `getTTD'
...Rotations\Rotations\Druid\Balance\BalanceLyLoLoq.lua:878: in function `actionList_Combat'
...Rotations\Rotations\Druid\Balance\BalanceLyLoLoq.lua:1490: in function `run'
...terface\AddOns\BadRotations\Rotations\cCharacter.lua:295: in function `startRotation'
Interface\AddOns\BadRotations\Rotations\cBuilder.lua:381: in function `update'
Interface\AddOns\BadRotations\System\Core.lua:177: in function <Interface\AddOns\BadRotations\System\Core.lua:137>

**Comment by LyLoLoq** [comment]
Is this still an issue?
