### ISSUE TITLE
Xavius dispel at 3 stacks debuff id

### ISSUE THREAD

**Issue by Druxlolz** [CuteOne/BadRotations#107]
Hello 

i was afk healing a lfr today and noticed that i got mind controlled because i had decurse active while on this boss.

I was able to get 2 ID's for the debuff it would just dispel it as soon as it comes but it should wait for 3 stacks before dispelling it :)

(LFR)
ID for debuff  206651, 209158

**Comment by kuukuukuatchu** [comment]
I usually just turned it off on that fight personally.  Can add to healing engine debuff check though.

**Comment by Druxlolz** [comment]
Would love to see it added, i'm checking every update trying to understand how lua works, so hopefully soon i can start helping out :)

**Comment by kuukuukuatchu** [comment]
Added, closing
