### ISSUE TITLE
 Priest profiles - Purify

### ISSUE THREAD

**Issue by newfriend1** [CuteOne/BadRotations#108]
The profiles are checking for Curse debuffs instead of Disease . Priests cant dispel curses with purify only Disease and Magic 

`if (bufftype == "Curse" or bufftype == "Magic") and lastSpell ~= spell.purify and isChecked("Purify") then`
Should be
`if (bufftype == "Disease" or bufftype == "Magic") and lastSpell ~= spell.purify and isChecked("Purify") then`

**Comment by SvsGit** [comment]
Fixed, thanks for report
