### ISSUE TITLE
Helya

### ISSUE THREAD

**Issue by itzjaayman** [CuteOne/BadRotations#109]
Bm hunter rotation is not working on helya

**Comment by Vilt-Coding** [comment]
What unlocker are you using, if firehack, what version?

**Comment by itzjaayman** [comment]
Yeah using 2.3.11 firehack and its just the targeting on the tentacles in first phase 
bad rotations wont use any attacking spells on them

**Comment by Vilt-Coding** [comment]
Try 2.3.12b5 https://firehack.io/firehack/FireHack%202.3.12b5zip

**Comment by itzjaayman** [comment]
404 not found for link

**Comment by Vilt-Coding** [comment]
try again

**Comment by itzjaayman** [comment]
Thank you will test tomorrow and let you know if its working

**Comment by itzjaayman** [comment]
Still having the same issue

**Comment by CuteOne** [comment]
It's a known problem, me and others have tried to get a solution from DK but not sure its going to happen at this point....currently investigating work arounds

**Comment by kuukuukuatchu** [comment]
Issue solved be resolved by patch 3 days ago. Is this still an issue?

**Comment by itzjaayman** [comment]
issue is resolved now thank you :)
