### ISSUE TITLE
getAuraDuration calling UnitBuffId

### ISSUE THREAD

**Issue by Bigsie** [CuteOne/BadRotations#1105]
No debuffs are taken into consideration

**Comment by kuukuukuatchu** [comment]
Unsure how this is an issue? That's a separate function for getting debuffs. 
function getDebuffDuration(Unit, DebuffID, Source)
	local duration = select(5, UnitDebuffID(Unit, DebuffID, Source))
	if duration ~= nil then
		duration = duration * 1
		return duration
	end
	-- if UnitDebuffID(Unit,DebuffID,Source) ~= nil then
	-- 	return select(5,UnitDebuffID(Unit,DebuffID,Source))*1
	-- end
	return 0
end

**Comment by Bigsie** [comment]
There is also getBuffDuration and getDebuffDuration that are obfuscating UnitDebuffID and UnitBuffID, imo **Aura** applies to both debuff and buff

**Comment by kuukuukuatchu** [comment]
Ya it's probably a pointless function really... it's basically just an alias for getBuffDuration in its current form and I don't know any case where you'd want to be checking both buff and debuffs at the same time.

**Comment by Bigsie** [comment]
Are enemies auras cast by an enemy, say a shield, debuffs or buffs?
