### ISSUE TITLE
BadRotations bug report

### ISSUE THREAD

**Issue by gaenari622** [CuteOne/BadRotations#1114]
Which Unlocker are you using?

Minibot

Do you have BugGrabber and BugSack Installed?

Yes

If Yes, please post the error below

BugGrabberDB = {
	["lastSanitation"] = 3,
	["session"] = 1,
	["errors"] = {
		{
			["message"] = "...face\\AddOns\\BadRotations\\System\\Functions\\Custom-Custom.lua:1040: attempt to call global 'GetMapId' (a nil value)",
			["time"] = "2021/01/12 19:35:53",
			["locals"] = "(*temporary) = <function> defined =[C]:-1\n(*temporary) = 2\n(*temporary) = nil\n(*temporary) = \"attempt to call global 'GetMapId' (a nil value)\"\n",
			["stack"] = "[string \"@Interface\\AddOns\\BadRotations\\System\\Functions\\Custom-Custom.lua\"]:1040: in function `getCurrentZoneId'\n[string \"BigMarksmanship.lua\"]:603: in function `CCs'\n[string \"BigMarksmanship.lua\"]:749: in function `run'\n[string \"@Interface\\AddOns\\BadRotations\\System\\Loader\\cCharacter.lua\"]:227: in function `startRotation'\n[string \"@Interface\\AddOns\\BadRotations\\System\\Loader\\cBuilder.lua\"]:563: in function `update'\n[string \"@Interface\\AddOns\\BadRotations\\System\\Core.lua\"]:189: in function <Interface\\AddOns\\BadRotations\\System\\Core.lua:70>",
			["session"] = 1,
			["counter"] = 148,
		}, -- [1]
		{
			["message"] = "...AddOns\\BadRotations\\System\\UI\\SettingsManagement.lua:196: attempt to get length of field '?' (a nil value)",
			["time"] = "2021/01/12 19:37:12",
			["locals"] = "self = nil\nsaveDir = \"D:\\World of Warcraft\\_retail_\\Interface\\AddOns\\BadRotations\\Settings\\Hunter\\\"\nspecID = nil\nrotationFound = false\n(*temporary) = 1\n(*temporary) = nil\n(*temporary) = \"Tracker\"\n(*temporary) = \"D:\\World of Warcraft\\_retail_\\Interface\\AddOns\\BadRotations\\Settings\\\"\n(*temporary) = \"D:\\World of Warcraft\\_retail_\\Interface\\AddOns\\BadRotations\\Settings\\Hunter\\\"\n(*temporary) = true\n(*temporary) = \"D:\\World of Warcraft\\_retail_\\Interface\\AddOns\\BadRotations\\Settings\\Hunter\\\"\n(*temporary) = \"attempt to get length of field '?' (a nil value)\"\n",
			["stack"] = "[string \"@Interface\\AddOns\\BadRotations\\System\\UI\\SettingsManagement.lua\"]:196: in function `saveLastProfileTracker'\n[string \"@Interface\\AddOns\\BadRotations\\BadRotations-1.33.7.lua\"]:189: in function <Interface\\AddOns\\BadRotations\\BadRotations.lua:168>",
			["session"] = 1,
			["counter"] = 1,
		}, -- [2]
	},
}

Which Class / Spec / Rotation Were you using during the bug.

hunter mm Cuteone

After a /reload were you able to reproduce the error?

Yes

Please give any other relevant information regarding the bug (Only happens in raid, open world, etc.)

January 11, 2021 version was very good
I switched to the version on January 12, 2021, and the following message appeared in the game.
There are too many errors in your UI

**Comment by LSharpAura** [comment]
Looks like the profile is calling a function that your unlocker doesn't have.  Probably an ewt only function would be my guess...and the person that wrote the profile didn't account for that.

**Comment by gaenari622** [comment]
Doesn't it support minibot anymore?
