### ISSUE TITLE
Queue casting disregard cast modes

### ISSUE THREAD

**Issue by iFeep** [CuteOne/BadRotations#1116]
**Submitted by:**
PeefTheBeast

**Which Unlocker are you using?**
EWT

**Do you have BugGrabber and BugSack Installed?**
Yes

**If Yes, please post the error below**
No Error

**Which Class / Spec / Rotation Were you using during the bug.**
Lak's resto druid, Aura's resto druid, but issue not related to specific profile

**After a /reload were you able to reproduce the error?**
Yes

**Please give any other relevant information regarding the bug (Only happens in raid, open world, etc.)**
Everywhere, in combat while spells are on gcd. The way i reproduce the issue:
Smart queue: on, 2 sec
Effloressence: on, Cursor

Instead of putting down Effloressence on the location of the cursor, it drops it down at the location of the targeted entity (enemy or friendly does not matter)

Video: https://screencast-o-matic.com/watch/crVlrDPdjH

**Comment by kuukuukuatchu** [comment]
Closing as unlocker no longer exists
