### ISSUE TITLE
Healthstones / Healing tonic + Keybinding

### ISSUE THREAD

**Issue by volcom790** [CuteOne/BadRotations#112]
The healing potions do not work, they are not used when I am at less than 30% HP.

Also the keybinding to enable / disable the use of CDs does not work, after putting my keybinding and pressed my key it does not work.

sorry for my bad english and good luck !

**Comment by Vilt-Coding** [comment]
Class/spec?

**Comment by volcom790** [comment]
After update, the keybinding works  correctly but the healing potions doesn't work.

Class: DK
Spec: Frost

My Blood DK rotation doesn't work on the P1 Helya (MoS) also.

**Comment by Vilt-Coding** [comment]
For Mos-Helya issue try FH 2.3.12b5 https://firehack.io/firehack/FireHack%202.3.12b5.zip
