### ISSUE TITLE
Better targeting for mythic+

### ISSUE THREAD

**Issue by MrClue** [CuteOne/BadRotations#113]
Please add a targeting feature, to **prioritise the explosive orbs over everything else** (skull first, dynamic targetting, should all have less value than explosive orbs).

As of right now, it wont target the orbs at all.

**Comment by Vilt-Coding** [comment]
Was added in https://github.com/CuteOne/BadRotations/commit/02a24e962da85a7470b8cfeb6c1fa3d2dcd7eb4d, turn on Dynamic Targetting and Forced Burn and it should focus them.

**Comment by kuukuukuatchu** [comment]
No further response so assuming resolved and closing.
