### ISSUE TITLE
Heal out of group allys in He active tab?

### ISSUE THREAD

**Issue by Dusktouge** [CuteOne/BadRotations#1135]
not a issue more of a question to be added, i was wondering if it was at all possible to add a option in the he active tab to write the a heal out of group targets checkbox and type box to write the allys name into so youre not running around healing npcs or just randoms all the time. It would be a nice option for those who farm in 2x4's or has a selective target they wanna heal in a raid. Thanks

**Comment by kuukuukuatchu** [comment]
What's wrong with using special heal and setting them as focus/target/mouseover?

**Comment by Dusktouge** [comment]
Well ill tell you, first you can only have one person set as focus and if
theres a way to add more then one then you gotta do all that manually and
move them, second if you use a holy pally like i do you tend to meele and
heal at the same time at times and using the dynamic targeting, targeting
wont work. The option cant be for me to turn off the targeting  system i
need to use for specific talents that recharges my holy shock. Third mouse
over option has got to be a joke right? For the instance i said in my post
you are replying to now. In a 2x4 farm youve got 30+ mobs around you and
your party memebers and the people i need to heal are in a nonstop movement
like they are suppose to. So if i mouseover itll end up targeting a enemy
or the wrong person. Its so much simplely to add a tab for non party
memebers and have atleast 5 boxs to add their toons name into so the
targeting system knows. Or you can setup a option to heal non party
memebers in a yard radius. That option will come in handy as well to the
addon not acting like a combat rotation bot and only selecting the party.
For instance a player near your group is talking to you saying heal me heal
me. And you can say its not some kind of botting system lol it requires you
to have a lua unlocker. And weall know theres only one thing to unlock
that. Thanks for hearing me out. Happy gaming.

**Comment by Dusktouge** [comment]
Also forgot to add some people havibg fps lag during a 2x4 farm in reven so
mouse over would be kinda hard there as well

**Comment by Dusktouge** [comment]
And those options only have a option for one person. Id like to see a
option like ive suggested for speical targets out of group that gives u the
option for up to 5 people.
