### ISSUE TITLE
spell to interrupt also a quick question 

### ISSUE THREAD

**Issue by Druxlolz** [CuteOne/BadRotations#115]
{ unitID = 99956, spell = 196799 }, -- Vault of Wardens http://www.wowhead.com/spell=196799/unleash-fury#used-by-npc

it should interrupt this ability as prio, not sure if it already do and if it doesn't should it be in   EnemiesEngineCollections.lua ?

**Comment by kuukuukuatchu** [comment]
Added on my local, will push next update
