### ISSUE TITLE
Troubleshoothing WMB

### ISSUE THREAD

**Issue by ahumado777** [CuteOne/BadRotations#1169]
![image](https://user-images.githubusercontent.com/79079477/107922153-3b134300-6f35-11eb-931d-75c948d644fc.png)

I don't understand what type of error is this, what can I do?

**Comment by kuukuukuatchu** [comment]
You would want to ask that in the support discord for Minibot.  We don't have any real support for it here.  The discord link for MB support is in the wiki.
