### ISSUE TITLE
(DH, Havoc) bug with Eye beam

### ISSUE THREAD

**Issue by MrClue** [CuteOne/BadRotations#118]
As of right now, it seems like the rotation is casting eye beam without checking how far away it is from the target.
Multiple times my DH is casting eye beam when it is too far away from the boss/targeted NPC.

**Comment by CuteOne** [comment]
Every eye beam has a check for number of units in its damage effect, you can actually hit targets from what looks like pretty far away...
![image](https://cloud.githubusercontent.com/assets/5498251/25019636/50d8b0c8-2059-11e7-89a6-33051434d6a4.png)

I was able to still hit the dummy from that point. Only possible thing I can think of is perhaps you or the target moved out of range after the code initiated to cast Eye Beam.

**Comment by MrClue** [comment]
I might be because the code is executing slow?
But it has happened like 10 times while i did mythic+ and mythic krosus.

**Comment by MrClue** [comment]
Nope definate using eye beam without checking distance. testet it more in mythic+ :p

**Comment by kuukuukuatchu** [comment]
Closing due to age and lack of comments, please reopen if still an issue
