### ISSUE TITLE
Shaman unleash life

### ISSUE THREAD

**Issue by Druxlolz** [CuteOne/BadRotations#120]
Hello can you make a toggle for Unleash life to only be used when next direct ability is chain heal? 

which would be like

Healing weave / Healing surge
Chain heal 
All

This would make legendary chain heal ring a lot better :)

since sometimes it uses unleash life with riptide which is a waist of cooldown / GCD, also with the new artifact unlock to cast double with you artifact weapon maybe it should be prioritized differently? 

Thx a lot for reading :)

**Comment by kuukuukuatchu** [comment]
Closing due to age.  Please reopen if issue persists.
