### ISSUE TITLE
Add option to not use Fel Rush while closing distance

### ISSUE THREAD

**Issue by Baconadors** [CuteOne/BadRotations#121]
This is a feature request. I am finding that when I use the Havoc DH routine, it is using Fel Rush to close distance, or using Fel Rush right after a Vengeful Retreat and traveling way further than it needs to.

I'd like to see a small change to Fel Rush. I'd suggest a tick box to ALWAYS animation cancel Fel Rush so that the character doesn't go too far.

EDIT: Just tested this again. the DH will use Fel Rush with the animation cancel. He doesn't use Vengeful Retreat, but still pops into the air and uses Fel Rush again, causing him to travel too far. Other times it will animation cancel both Fel Rushes without issue. It just seems pretty inconsistent.

**Comment by CuteOne** [comment]
This issue could be related to lag as its all a timing thing with the cancel, for me its been 100%

**Comment by Baconadors** [comment]
You may be right about it being lag. I did notice that when I load FH and start the havoc rotation, my ping will shoot up from ~70-80 to 130+ after a few minutes.
(right is world ping)
http://i.imgur.com/2b8aQNi.png
to
http://i.imgur.com/Z5BPmLh.png

After watching it mess up more, it seems to do the animation cancel then fel rush. Would you have any clue as to why this is happening to me?

**Comment by Baconadors** [comment]
I'll actually write back after I deal with Comcast. My internet has been steadily getting worse over the past few days and I think that's my issue. I now average 300ms when I should be well below 100.
