### ISSUE TITLE
FrostCuteOne.lua  BUG

### ISSUE THREAD

**Issue by 52nt** [CuteOne/BadRotations#1218]
Total error of ice DK Lua in use:
Code: 487 lines
Delete this code, will not report errors in the output cycle smooth!

![0B013F6DA44F282BA5DC2496C6D9E7FC](https://user-images.githubusercontent.com/38102375/112405803-f3f74980-8d4d-11eb-8d01-50ef81956811.png)

**Comment by kuukuukuatchu** [comment]
Issue should be resolved, closing.
