### ISSUE TITLE
DisciplineBizkut.lua

### ISSUE THREAD

**Issue by newfriend1** [CuteOne/BadRotations#123]
` if (bufftype == "Disease" or bufftype == "Curse" or bufftype == "Magic")` 
to
` if (bufftype == "Disease" or bufftype == "Magic")` 

Priest cannot remove curse

**Comment by bizkut** [comment]
I forgot to take it out when testing the spell. Thank you for the report

**Comment by bizkut** [comment]
Fixed. case closed
