### ISSUE TITLE
DestroKink.lua

### ISSUE THREAD

**Issue by blood5858** [CuteOne/BadRotations#1237]
-- Cataclysm
            -- cataclysm,if=!(pet.infernal.active&dot.immolate.remains+1>pet.infernal.remains)|spell_targets.cataclysm>1|!talent.grimoire_of_supremacy.enabled
            if br.timer:useTimer("Cata Delay", 1) and mode.cataclysm == 1 and ui.checked("Cataclysm") and not moving and cd.cataclysm.remain() <= gcdMax and (not (pet.infernal.active()
            and debuff.immolate.remain("target") + 1 > infernalRemain) or (#enemies.yards8t >= ui.value("Cataclysm Units")
            or (br.useCDs() and ui.checked("Ignore Cataclysm units when using CDs"))) or not talent.grimoireOfSupremacy)

---------------------------------
--Cataclysm
            -- cataclysm,if=!(pet.infernal.active&dot.immolate.remains+1>pet.infernal.remains)|spell_targets.cataclysm>1|!talent.grimoire_of_supremacy.enabled
            if br.timer:useTimer("Cata Delay", 0) and mode.cataclysm == 1 and ui.checked("Cataclysm") and not moving and cd.cataclysm.remain() <= gcdMax and (not (pet.infernal.active()
            and debuff.immolate.remain("target") + 1 > infernalRemain) or (#enemies.yards8t >= ui.value("Cataclysm Units")
            or (br.useCDs() and ui.checked("Ignore Cataclysm units when using CDs"))) or not talent.grimoireOfSupremacy)

works better for me can u check RoF too

**Comment by kuukuukuatchu** [comment]
I don't understand the point of this.  All you're doing is removing the delay completely.  You might as well just remove br.timer:useTimer("Cata Delay", 0) completely in this code as it's doing nothing.  Also Kink is no longer working on BR so I doubt his profile will be updated anymore.
