### ISSUE TITLE
Which spec is least reliant on lua unlocker?

### ISSUE THREAD

**Issue by quetzalsly** [CuteOne/BadRotations#1261]
I really want to try BR but I just dont like going down the territory of lua unlockers. Is there a certain spec that can go without calling lua protected functions? I am guessing something that does not need to multi dot, just mash buttons on a single target? any suggestions?

**Comment by kuukuukuatchu** [comment]
In order to run, BR requires an unlocker.  If you don't have one, BR won't run at all.

**Comment by quetzalsly** [comment]
Right I see, thats really sad. I have no problem using lua unlockers on a random alt account I dont care about, but playing my main account it just has too much sentimental value to risk using unlockers. Lets say I was somehow able to edit BR to not call protected functions though, which class/spec would be best do you think?

**Comment by CuteOne** [comment]
That would be quite the undertaking.

**Comment by kuukuukuatchu** [comment]
Being as you wouldn't be able to cast or use anything if you're not calling protected functions.... none of them.

**Comment by quetzalsly** [comment]
Whats wrong with just displaying a pixel and having an external app read it? I understand that its not as optimal as calling the functions directly, but at least its a lot safer than lua unlockers, right now I feel like blizzard is simply allowing bots to exist because it brings them a lot of revenue. There are so many ways I can think of to detect someone calling these protected functions.

**Comment by kuukuukuatchu** [comment]
Nothing wrong with it, but BR is not a pixel bot and we have no interest in making it a pixel bot.  Also, pixel bots get detected just as much as any other bot so it's not "a lot safer than lua unlockers".   If they were actually any safer, you would see more of them. 

To answer your actual question though, I'd suggest looking at what performs best with things like Gnome Sequencer Enhanced as that's essentially what removing the unlocker's capabilities would turn BR into.
