### ISSUE TITLE
Wow has stopped working

### ISSUE THREAD

**Issue by Aleksaas** [CuteOne/BadRotations#130]
Anyone has this issue? I am getting it very often. It crashes twice an hour approximately. It doesnt happen when I disable BadRotations addon.

**Comment by Druxlolz** [comment]
lower karazhan and upper i have huge lags to but when disable rotation everything is fine probably duo to bad pathing? sorry for hijacking but might also be you lua unlocker if firehack they have many problems

**Comment by Aleksaas** [comment]
I deleted the content of Cache, WTF and Data/indices folders and it seems that fixed the issue. You can close this.
