### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Makia67** [CuteOne/BadRotations#1307]
Message: [string ""]:611: 'for' limit must be a number
Time: Wed Oct 26 19:42:55 2022
Count: 1
Stack: [string ""]:611: 'for' limit must be a number
[string ""]:611: in function BuildInfo'
[string ""]:285: in function eventhandler'
[string ""]:133: in function <[string ""]:131>

Locals: self = <table> {
 PLAYER_LOGOUT = <function> defined :289
 UpdateCommScope = <function> defined :758
 cache = <table> {
 }
 PLAYER_LOGIN = <function> defined :267
 PLAYER_ENTERING_WORLD = <function> defined :678
 BuildInfo = <function> defined :558
 GetCachedPvpTalentInfoByID = <function> defined :374
 GROUP_ROSTER_UPDATE = <function> defined :689
 INSPECT_READY = <function> defined :649
 NotifyInspect = <function> defined :162
 UpdatePlayerInfo = <function> defined :542
 UnregisterAllCallbacks = <function> defined :200
 SendLatestSpecData = <function> defined :721
 static_cache = <table> {
 }
 CacheGameData = <function> defined :393
 GetCachedTalentInfo = <function> defined :332
 DoPlayerUpdate = <function> defined :715
 Refresh = <function> defined :451
 ProcessQueues = <function> defined :465
 RegisterCallback = <function> defined :116
 state = <table> {
 }
 GetCachedTalentInfoByID = <function> defined :353
 UnregisterCallback = <function> defined :179
 Query = <function> defined :430
 GuidToUnit = <function> defined :414
 frame = LibGroupInSpecT-1.1_Frame {
 }
 hooked = true
 events = <table> {
 }
}
unit = "player"
guid = "Player-1621-0AFA3C4B"
cache = <table> {
 Player-1621-0AFA3C4B = <table> {
 }
}
info = <table> {
 class_id = 11
 guid = "Player-1621-0AFA3C4B"
 class = "DRUID"
 spec_description = "Prend la forme d’un grand félin pour infliger des dégâts de saignement et des morsures.
Armes : bâtons et armes d’hast."
 spec_icon = 132115
 race = "NightElf"
 spec_background = "DAMAGER"
 class_localized = "Druidesse"
 lku = "player"
 global_spec_id = 103
 pvp_talents = <table> {
 }
 spec_index = 2
 gender = 3
 spec_role = "DAMAGER"
 spec_group = 1
 name = "Mak****"
 talents = <table> {
 }
 race_localized = "Elfe de la nuit"
 spec_role_detailed = "melee"
 spec_name_localized = "Farouche"
}
class = "DRUID"
is_inspect = false
spec = 2
gspec_id = 103
gspecs = <table> {
 0 = <table> {
 }
 62 = <table> {
 }
 1467 = <table> {
 }
 63 = <table> {
 }
 250 = <table> {
 }
 251 = <table> {
 }
 252 = <table> {
 }
 1468 = <table> {
 }
 253 = <table> {
 }
 254 = <table> {
 }
 255 = <table> {
 }
 256 = <table> {
 }
 257 = <table> {
 }
 258 = <table> {
 }
 259 = <table> {
 }
 260 = <table> {
 }
 261 = <table> {
 }
 262 = <table> {
 }
 263 = <table> {
 }
 264 = <table> {
 }
 265 = <table> {
 }
 266 = <table> {
 }
 267 = <table> {
 }
 268 = <table> {
 }
 269 = <table> {
 }
 270 = <table> {
 }
 70 = <table> {
 }
 102 = <table> {
 }
 71 = <table> {
 }
 103 = <table> {
 }
 72 = <table> {
 }
 104 = <table> {
 }
 73 = <table> {
 }
 581 = <table> {
 }
 105 = <table> {
 }
 577 = <table> {
 }
 64 = <table> {
 }
 66 = <table> {
 }
 65 = <table> {
 }
[19:45]
}
(for index) = 1
(for limit) = nil
(for step) = 1
(temporary) = 132115
(temporary) = "DAMAGER"
(temporary) = 2
(temporary) = ""
(temporary) = "Mak**"
(temporary) = ""
(temporary) = nil
(temporary) = nil
(temporary) = nil
(temporary) = nil
(temporary) = nil
(temporary) = nil
(temporary) = nil
(temporary) = "'for' limit must be a number"
UnitGUID = <function> defined =[C]:-1
QUEUE_EVENT = "GroupInSpecT_QueueChanged"
UnitIsUnit = <function> defined =[C]:-1
GetSpecialization = <function> defined =[C]:-1
GetInspectSpecialization = <function> defined =[C]:-1
GetSpecializationInfo = <function> defined =[C]:-1
global_spec_id_roles_detailed = <table> {
 62 = "ranged"
 63 = "ranged"
 250 = "tank"
 251 = "melee"
 252 = "melee"
 253 = "ranged"
 254 = "ranged"
 255 = "melee"
 66 = "tank"
 257 = "healer"
 258 = "ranged"
 259 = "melee"
 260 = "melee"
 577 = "melee"
 262 = "ranged"
 581 = "tank"
 264 = "healer"
 265 = "ranged"
 266 = "ranged"
 267 = "ranged"
 268 = "tank"
 269 = "melee"
 270 = "healer"
 70 = "melee"
 102

**Comment by CuteOne** [comment]
Unfortunately at this time the following does not seem to be an error on BR's end as its not even trying to load which would suggest an issue with the unlocker.

**Comment by CuteOne** [comment]
Forgot to mention here, mentioned in discord, but this is now resolved. Thanks for reporting it.
