### ISSUE TITLE
Balance Druid - CC and AOE lag

### ISSUE THREAD

**Issue by MrClue** [CuteOne/BadRotations#131]
So i've noticed, that everytime my druid gets CC'ed in raids the rotation starts lagging the game, or atleast giving it a very low frame rate?

Also on AOE pulls 6+ enemies, the game has low FPS. When i toggle off rotation, the FPS goes back to normal, so it is not my computer :p

**Comment by MrClue** [comment]
I think i know why this is happening on AOE now...
When using automatic dynamic targeting on more than 4 adds, it makes wow have low FPS.

I think the main problem with low FPS will be solved if you fix the targetting :)

**Comment by kuukuukuatchu** [comment]
Closing due to various improvements to FPS issues since post.  Please reopen if still an issue
