### ISSUE TITLE
Holy Priest 

### ISSUE THREAD

**Issue by newfriend1** [CuteOne/BadRotations#133]
`4x ...dRotations\System\Engines\HealingEngineFunctions.lua:73: attempt to perform arithmetic on local 'X2' (a nil value)
...dRotations\System\Engines\HealingEngineFunctions.lua:73: in function `getNovaDistance'
...dRotations\System\Engines\HealingEngineFunctions.lua:96: in function `getUnitsToHealAround'
...dRotations\System\Engines\HealingEngineFunctions.lua:47: in function `castWiseAoEHeal'
...ddOns\BadRotations\Rotations\Priest\Holy\HolySvs.lua:411: in function `actionList_Divinity'
...ddOns\BadRotations\Rotations\Priest\Holy\HolySvs.lua:576: in function `run'
BadRotations\Rotations\cCharacter.lua:293: in function `startRotation'
BadRotations\Rotations\cBuilder.lua:383: in function `update'
BadRotations\System\Core.lua:196: in function <BadRotations\System\Core.lua:151>

Locals:`

**Comment by kuukuukuatchu** [comment]
Closing as issue has been resolved as far as we know.  Please reopen if still an issue
