### ISSUE TITLE
DK Blood -- attempt to cast.deathAndDecay using "playerGround" or "player" fails

### ISSUE THREAD

**Issue by BrewingCoder** [CuteOne/BadRotations#1346]
trying to get death and decay to cast at the foot of the player, similar to the command "/cast [@player] Death and Decay"

using cast.deathAndDecay("player",nil,1,8)   fails to cast and returns FALSE.  this is already inside a target distance check of < 5 so we know at least 1 target is inside the AOE radius.

using the documented "playerGround" unit name the following error occurs:

414x [string "BadRotations/System/Functions/Custom.lua"]:103: attempt to perform arithmetic on a table value
[string "BadRotations/System/Functions/Custom.lua"]:103: in function <[string "BadRotations/System/Functions/Custom.lua"]:93>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "BrewBloodKnight.lua"]:253: in function `run'
[string "BadRotations/System/Loader/cCharacter.lua"]:222: in function `startRotation'
[string "BadRotations/System/Loader/cBuilder.lua"]:436: in function `update'
[string "BadRotations/System/Core.lua"]:222: in function <[string "BadRotations/System/Core.lua"]:98>

Locals:
spellID = 43265
radius = 8
minUnits = 0
maxRange = 30
minRange = 0
spellType = "norm"
unit = "player"
_ = "Death and Decay"
_ = nil
_ = 136144
_ = 0
spellMinRange = 0
spellMaxRange = 30
allUnitsInRange = nil
(*temporary) = <table> {
 1 = "Creature-0-4224-1159-17660-87318-0000464C22"
 2 = "Creature-0-4224-1159-17660-88314-0000464C22"
}
(*temporary) = <table> {
}
(*temporary) = "player"
(*temporary) = 0
(*temporary) = true
(*temporary) = false
(*temporary) = 236710742.918100
(*temporary) = <table> {
 Creature-0-4224-1159-17660-87318-0000464C22 = <table> {
 }
 Creature-0-4224-1159-17660-88314-0000464C22 = <table> {
 }
}
(*temporary) = <table> {
}
(*temporary) = "Creature-0-4224-1159-17660-88314-0000464C22"
(*temporary) = "attempt to perform arithmetic on a table value"
br = <table> {
 lastCastTable = <table> {
 }
 storedTables = <table> {
 }
 castGroundAtLocation = <function> defined BadRotations/System/Engines/HealingEngineFunctions.lua:550
 getFallDistance = <function> defined BadRotations/System/Functions/Misc.lua:21
 getRecharge = <function> defined BadRotations/System/Functions/Spell.lua:182
 canUseItem = <function> defined BadRotations/System/Functions/Item.lua:11
 getDebuffMinMax = <function> defined BadRotations/System/Functions/Aura.lua:407
 selectedProfile = 1
 UnitAuraID = <function> defined BadRotations/System/Functions/Aura.lua:29
 getUnits = <function> defined BadRotations/System/Functions/Custom.lua:72
 healConeAround = <function> defined BadRotations/System/Engines/HealingEngineFunctions.lua:360
 debug = <table> {
 }
 getTotemDistance = <function> defined BadRotations/System/Functions/Range.lua:202
 getHeirloomNeck = <function> defined BadRotations/System/Lists/Items.lua:3
 getOptionText = <function> defined BadRotations/System/Functions/Misc.lua:838
 canCast = <function> defined BadRotations/System/Functions/Cast.lua:3
 AuraData = <function> defined BadRotations/System/Functions/Aura.lua:2
 druid = <table> {
 }
 getOptionValue = <function> defined BadRotations/System/Functions/Misc.lua:835
 fallDist = 0
 getThreat = <function> defined BadRotations/System/Functions/Custom.lua:347
 castSpell = <function> defined BadRotations/System/Functions/Cast.lua:227
 canDisarm = <function> defined BadRotations/System/Functions/Combat.lua:32
 cancelBuff = <function> defined BadRotations/System/Functions/Custom.lua:615
 isHumanoid = <function> defined BadRotations/System/Functions/Unit.lua:381
 settingsDir = "\"
 data = <table> {
 }
 getGlobalCD = <function> defined BadRotations/System/Functions/Spell.lua:242
 isMoving = <function> defined BadRotations/System/Functions/Misc.lua:415
 rotations = <table> {
 }
 loader = <table> {
 }
 lootManager = <table> {
 }
 isLongTimeCCed = <function> defined BadRotations/System/Functions/Misc.lua:394
 hasBuff = <function> defined BadRotations/System/Functions/Custom.lua:598
 ComboMaxSpend = <function> defined BadRotations/System/Loader/cBuilder.lua:634
 castSpellMacro = <function> defined BadRotations/System/Functions/Cast.lua:332
 SpecificToggle = <function> defined BadRotations/System/Functions/Misc.lua:597
 getFallTime = <function> defined BadRotations/System/Functions/Misc.lua:42
 GetObjectPosition = <function> defined BadRotations/System/Functions/Unit.lua:46
 lists = <table> {
 }
 engines = <table> {
 }
 getGround = <function> defined BadRotations/System/Functions/Misc.lua:242
 spellDebug = <function> defined BadRotations/System/Functions/Misc.lua:764
 getNonExecuteEnemiesPercent = <function> defined BadRotations/System/Engines/EnemiesEngineFunctions.lua:626
 isNotBlacklisted = <function> defined BadRotations/System/Functions/Custom.lua:84
 devMode = <function> defined BadRotations/System/Functions/Misc.lua:870
 isUnitCasting = <function> defined BadRotations/System/Functions/Cast.lua:564
 getLowAllies = <function> defined BadRotations/System/Functions/Combat.lua:84
 PullTimerRemain = <function> defined BadRotations/System/Functions/Custom.lua:870
 getHealthPot = <function> defined BadRotations/System/Functions/Item.lua:126
 timeOfLastLoadingScreen = 236695.996000
 castingUnit = <

**Comment by CuteOne** [comment]
I pushed an update that should solve the issue using "playerGround", is you want to use just "player" then I'd use it like this,  cast.deathAndDecay("player","ground",1,8) so it will handle it properly.

**Comment by BrewingCoder** [comment]
78x [string "BadRotations/System/Functions/Custom.lua"]:74: attempt to get length of local 'allUnitsInRange' (a number value)
[string "BadRotations/System/Functions/Custom.lua"]:74: in function `getUnits'
[string "BadRotations/System/Functions/Custom.lua"]:109: in function <[string "BadRotations/System/Functions/Custom.lua"]:93>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "BrewBloodKnight.lua"]:253: in function `run'
[string "BadRotations/System/Loader/cCharacter.lua"]:222: in function `startRotation'
[string "BadRotations/System/Loader/cBuilder.lua"]:436: in function `update'
[string "BadRotations/System/Core.lua"]:222: in function <[string "BadRotations/System/Core.lua"]:98>

Locals:
thisUnit = "player"
allUnitsInRange = 2
radius = 5
unitsAroundThisUnit = <table> {
}
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to get length of local 'allUnitsInRange' (a number value)"
br = <table> {
 lastCastTable = <table> {
 }
 storedTables = <table> {
 }
 castGroundAtLocation = <function> defined BadRotations/System/Engines/HealingEngineFunctions.lua:550
 getFallDistance = <function> defined BadRotations/System/Functions/Misc.lua:21
 getRecharge = <function> defined BadRotations/System/Functions/Spell.lua:182
 canUseItem = <function> defined BadRotations/System/Functions/Item.lua:11
 getDebuffMinMax = <function> defined BadRotations/System/Functions/Aura.lua:407
 selectedProfile = 1
 UnitAuraID = <function> defined BadRotations/System/Functions/Aura.lua:29
 getUnits = <function> defined BadRotations/System/Functions/Custom.lua:72
 healConeAround = <function> defined BadRotations/System/Engines/HealingEngineFunctions.lua:360
 debug = <table> {
 }
 getTotemDistance = <function> defined BadRotations/System/Functions/Range.lua:202
 getHeirloomNeck = <function> defined BadRotations/System/Lists/Items.lua:3
 getOptionText = <function> defined BadRotations/System/Functions/Misc.lua:838
 canCast = <function> defined BadRotations/System/Functions/Cast.lua:3
 AuraData = <function> defined BadRotations/System/Functions/Aura.lua:2
 druid = <table> {
 }
 getOptionValue = <function> defined BadRotations/System/Functions/Misc.lua:835
 fallDist = 0
 getThreat = <function> defined BadRotations/System/Functions/Custom.lua:435
 castSpell = <function> defined BadRotations/System/Functions/Cast.lua:227
 canDisarm = <function> defined BadRotations/System/Functions/Combat.lua:32
 cancelBuff = <function> defined BadRotations/System/Functions/Custom.lua:703
 isHumanoid = <function> defined BadRotations/System/Functions/Unit.lua:381
 settingsDir = "\"
 data = <table> {
 }
 getGlobalCD = <function> defined BadRotations/System/Functions/Spell.lua:242
 isMoving = <function> defined BadRotations/System/Functions/Misc.lua:415
 rotations = <table> {
 }
 loader = <table> {
 }
 lootManager = <table> {
 }
 isLongTimeCCed = <function> defined BadRotations/System/Functions/Misc.lua:394
 hasBuff = <function> defined BadRotations/System/Functions/Custom.lua:686
 ComboMaxSpend = <function> defined BadRotations/System/Loader/cBuilder.lua:634
 castSpellMacro = <function> defined BadRotations/System/Functions/Cast.lua:332
 SpecificToggle = <function> defined BadRotations/System/Functions/Misc.lua:597
 getFallTime = <function> defined BadRotations/System/Functions/Misc.lua:42
 GetObjectPosition = <function> defined BadRotations/System/Functions/Unit.lua:46
 lists = <table> {
 }
 engines = <table> {
 }
 getGround = <function> defined BadRotations/System/Functions/Misc.lua:242
 spellDebug = <function> defined BadRotations/System/Functions/Misc.lua:764
 getNonExecuteEnemiesPercent = <function> defined BadRotations/System/Engines/EnemiesEngineFunctions.lua:626
 isNotBlacklisted = <function> defined BadRotations/System/Functions/Custom.lua:84
 devMode = <function> defined BadRotations/System/Functions/Misc.lua:870
 isUnitCasting = <function> defined BadRotations/System/Functions/Cast.lua:564
 getLowAllies = <function> defined BadRotations/System/Functions/Combat.lua:84
 PullTimerRemain = <function> defined BadRotations/System/Functions/Custom.lua:958
 getHealthPot = <function> defined BadRotations/System/Functions/Item.lua:126
 timeOfLastLoadingScreen = 240875.578000
 castingUnit = <function> defined BadRotations/System/Functions/Cast.lua:529
 isActiveEssence = <function> defined BadRotations/System/Functions/Spell.lua:329
 checkBrOutOfDate = <function> defined BadRotations/System/Unlockers.lua:31
 textInterrupt = FontString {
 }
 canFly = <function> defined BadRotations/System/Functions/Action.lua:2
 getCharges = <function> defined BadRotations/System/Functions/Spell.lua:161
 isAggroed = <function> defined BadRotations/System/Functi

**Comment by CuteOne** [comment]
Updated again, I see that it needs to be table return so I fixed it to properly remove the min range units from the max range units table instead of just the counts.
