### ISSUE TITLE
[DH, Havoc] Suggestion for DPS increase in raids

### ISSUE THREAD

**Issue by MrClue** [CuteOne/BadRotations#135]
I am raiding on mythic lvl, and i've got a few suggestions that you should implement :)

#1 
When fighting a raid boss, add an option to use the Artifact Ability "Fury of the Illidari" on cooldown + burst mode.
At the moment it is not using it properly on cooldown, even though you tick the option in the drop down menu.

#2 
 Add an option to use rings such as Gnawed Thumb, or even trinkets with use effects such as Horn of Valor or the one that increases secondary stats.
For these items there should be an option, to enable them for burst mode only and an option to use them on cooldown. 

Link to ring: http://www.wowhead.com/item=134526/gnawed-thumb-ring&bonus=1826
Link to trinket: http://www.wowhead.com/item=133642/horn-of-valor&bonus=1826

**Comment by CuteOne** [comment]
Thank you for the suggestions I will see what I can do been busy with college finals

**Comment by kuukuukuatchu** [comment]
Closing due to age.  Please reopen if issue persists.
