### ISSUE TITLE
Ench Shaman - Stormbringer issue

### ISSUE THREAD

**Issue by darhanger** [CuteOne/BadRotations#136]
Hello! Perhaps my request is ignored. I asked several times to make sure that the bot spammed stormstrike when stormbringer proс

**Comment by CuteOne** [comment]
It already does that according to simc
`actions+=/stormstrike,if=buff.stormbringer.react&((talent.fury_of_air.enabled&maelstrom>=26)|(!talent.fury_of_air.enabled))`

**Comment by kuukuukuatchu** [comment]
Closed due to 7.2.5 update. Please reopen if issue persists.
