### ISSUE TITLE
balance druid rotation not working with legendary gear

### ISSUE THREAD

**Issue by cromatom** [CuteOne/BadRotations#137]
the rotation will not cast full moon and when in single mode will not cast starsurge properly,this happens when using "The Emerald Dreamcatcher" legendary head piece,this legendary reduces starsurge astral power cost by 7 for 3 secs, i can confirm this is caused when using the lengendary,i have tried with feral,and resto legendaries on,and the rotation casts full moon and starsurge normally.also another big isssue i have encouter is that incarnation chosen of elune/celestial alignment and honor talen "Eclipse" will make the rotation do nothing when youre not moving,if u move the rotation will cast starsurge and dot enemies for the duration of the buffs,excuse my bad english

**Comment by kuukuukuatchu** [comment]
Closing due to age.  Please reopen if still an issue.
