### ISSUE TITLE
Frost Mage - Dismount into summon water elemental

### ISSUE THREAD

**Issue by Druxlolz** [CuteOne/BadRotations#139]
Hello.

I just want to let u guys know that every time i dismount as frost mage with CuteOne rotation, it seems to try summon water elemental every time i'm dismounting like it doesn't see that it's already active, since when i move (cancel it) it will not stay summon it again since it has like 1-2 sec before appearing after dismount (the water elemental)

**Comment by LyLoLoq** [comment]
thanks for the report.

**Comment by kuukuukuatchu** [comment]
Closing due to age.  Please reopen if still an issue.
