### ISSUE TITLE
Retribution Paladin - Divine Hammer Usage

### ISSUE THREAD

**Issue by DupKan** [CuteOne/BadRotations#140]
Is there a way for its priority to be lowered if the paladin has 4 holy power or more to below divine storm or templar's verdict. It will use Divine Hammer or Blade of Wrath if you have 4 or 5 holy power and "waste" that power.

**Comment by DupKan** [comment]
This happens specifically if you disable the use of Wake of Ashes in the options.

**Comment by CuteOne** [comment]
Closed due to profile rewrite for 7.2.5
