### ISSUE TITLE
LUA issue

### ISSUE THREAD

**Issue by Mcgryan** [CuteOne/BadRotations#143]
essage: Interface\AddOns\AtlasLoot\Core\ItemInfo.lua:379: table index is nil
Time: 05/24/17 13:05:08
Count: 1
Stack: Interface\AddOns\AtlasLoot\Core\ItemInfo.lua:379: in function `func'
Interface\AddOns\AtlasLoot\AtlasLoot.lua:37: in function <Interface\AddOns\AtlasLoot\AtlasLoot.lua:29>

Locals: itemClasses = <table> {
 1 = <table> {
 }
}
(for index) = 1
(for limit) = 1
(for step) = 1
i = 1
itemSubClasses = <table> {
 1 = 0
 2 = 2
 3 = 3
 4 = 4
 5 = 5
 6 = 6
 7 = 7
 8 = 8
 9 = 9
 10 = 10
}
iTab = <table> {
 Two-Handed Maces = "Two-Hand, Mace"
 2 = "Two-Hand, Axe"
 4 = "Gun"
 8 = "One-Hand, Sword"
 One-Handed Swords = "One-Hand, Sword"
 Staves = "Staff"
 Crossbows = "Crossbow"
 10 = "Staff"
 Polearms = "Polearm"
 One-Handed Maces = "One-Hand, Mace"
 3 = "Bow"
 6 = "Two-Hand, Mace"
 9 = "Two-Hand, Sword"
 7 = "Polearm"
 Daggers = "Dagger"
 Two-Handed Swords = "Two-Hand, Sword"
 5 = "One-Hand, Mace"
 One-Handed Axes = "One-Hand, Axe"
 0 = "One-Hand, Axe"
 Guns = "Gun"
 Fist Weapons = "Fist Weapon"
 Fishing Poles = "Fishing Pole"
 Wands = "Wand"
 Bows = "Bow"
 Two-Handed Axes = "Two-Hand, Axe"
}
(for index) = 11
(for limit) = 17
(for step) = 1
j = 11
(*temporary) = nil
(*temporary) = "Fist Weapon"
(*temporary) = nil
(*temporary) = "table index is nil"
LOC_DATA = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 translation = <table> {
 }
}
ITEM_DESC_INFO = <table> {
 Armor = <table> {
 }
 (null) = <table> {
 }
 Weapon = <table> {
 }
 slot = <table> {
 }
}
rawget = <function> defined =[C]:-1
IngameLocales = <table> {
 Windwalker = "Windwalker"
 Shadow = "Shadow"
 ROGUE = "Rogue"
 Unholy = "Unholy"
 Ahn'Qiraj = "Ahn'Qiraj"
 February = "February"
 Retribution = "Retribution"
 Orgrimmar = "Orgrimmar"
 Old Hillpaw = "Old Hillpaw"
 Discipline = "Discipline"
 Feral = "Feral"
 Stormwind City = "Stormwind City"
 Karazhan = "Karazhan"
 Mistweaver = "Mistweaver"
 August = "August"
 Guardian = "Guardian"
 DEMONHUNTER = "Demon Hunter"
 Lower Blackrock Spire = "Lower Blackrock Spire"
 April = "April"
 Protection = "Protection"
 Bizmo's Brawlpub = "Bizmo's Brawlpub (Season 2)"
 SHAMAN = "Shaman"
 Ruins of Ahn'Qiraj = "Ruins of Ahn'Qiraj"
 Frost = "Frost"
 Dalaran = "Dalaran"
 September = "September"
 DEATHKNIGHT = "Death Knight"
 January = "January"
 Staves = 10
 March = "March"
 Nat Pagle = "Nat Pagle"
 Molten Front = "Molten Front"
 Two-Handed Swords = 9
 Timeless Isle = "Timeless Isle"
 July = "July"
 One-Handed Swords = 8
 Northrend = ""
 May = "May"
 Two-Handed Maces = 6
 Sho = "Sho"
 One-Handed Maces = 5
 Guns = 4
 October = "October"
 PALADIN = "Paladin"
 MAGE = "Mage"
 PRIEST = "Priest"
 Outland = ""
 The Tannery = "The Tannery"
 Brawl'gar Arena = "Brawl'gar Arena (Season 2)"
 Scarlet Monastery = "Scarlet Monastery"
 The Ruby Sanctum = "The Ruby Sanctum"
 Two-Handed Axes = 2
 Arms = "Arms"
 Naxxramas = "Naxxramas"
 MONK = "Monk"
 One-Handed Axes = 0
 WARRIOR = "Warrior"
 December = "December"
 Elemental = "Elemental"
 Engineering Works = "Engineering Works"
 Hyjal Summit = "Hyjal Summit"
 Bows = 3
 HUNTER = "Hunter"
 Sunwell Plateau = "Sunwell Plateau"
 Vault of Archavon = "Vault of Archavon"
 DRUID = "Druid"
 WARLOCK = "Warlock"
 Shattrath City = "Shattrath City"
 Shadowfang Keep = "Shadowfang Keep"
 LIFT = "Lunarfall Inn"
 Molten Core = "Molten Core"
 The Slave Pens = "The Slave Pens"
 Icecrown = "Icecrown"
 Fishing Shack = "Fishing Shack"
 Enchanter's Study = "Enchanter's Study"
 The August Celestials = "The August Celestials"
 Gruul's Lair = "Gruul's Lair"
 DBWM = "Dwarven Bunker"
 Ulduar = "Ulduar"
 Upper Blackrock Spire = "Upper Blackrock Spire (Classic)"
 Trial of the Crusader = "Trial of the Crusader"
 Balance = "Balance"
 The Obsidian Sanctum = "The Obsidian Sanctum"
 The Eye of Eternity = "The Eye of Eternity"
 Onyxia's Lair = "Onyxia's Lair"
 Polearms = 7
 Icecrown C

**Comment by kuukuukuatchu** [comment]
That's an issue with Atlas loot by the looks of the message.

**Comment by Mcgryan** [comment]
this issue never happens tell I load up BR an FH

**Comment by kuukuukuatchu** [comment]
Oh if you're using the latest fh beta that's a known issue with it that l0l1dk said will be fixed in next major release.
