### ISSUE TITLE
Tier 20 bonus 1 tweak? - Frost Mage

### ISSUE THREAD

**Issue by Druxlolz** [CuteOne/BadRotations#151]
Hello.
Tier 20 Set bonus 1 - If frozen orb is 5-10sec off cooldown maybe we shouldn't be casting our ice lance procs before frozen orb is active? i think we better of holding on to them till frozen orb is active i think?

**Comment by kuukuukuatchu** [comment]
Resolved in updates since posted.  Please reopen if still an issue.
