### ISSUE TITLE
EnhancementCuteOne.lua:428

### ISSUE THREAD

**Issue by darhanger** [CuteOne/BadRotations#152]
Message: ...\Rotations\Shaman\Enhancement\EnhancementCuteOne.lua:428: attempt to call global 'hasLust' (a nil value)
Time: 06/23/17 22:21:38
Count: 35
Stack: ...\Rotations\Shaman\Enhancement\EnhancementCuteOne.lua:428: attempt to call global 'hasLust' (a nil value)Interface\SharedXML\SharedBasicControls.lua:204: in function <Interface\SharedXML\SharedBasicControls.lua:203>
[C]: in function `hasLust'
...\Rotations\Shaman\Enhancement\EnhancementCuteOne.lua:428: in function `actionList_Cooldowns'
...\Rotations\Shaman\Enhancement\EnhancementCuteOne.lua:744: in function `run'
...terface\AddOns\BadRotations\Rotations\cCharacter.lua:296: in function `startRotation'
Interface\AddOns\BadRotations\Rotations\cBuilder.lua:381: in function `update'
Interface\AddOns\BadRotations\System\Core.lua:206: in function <Interface\AddOns\BadRotations\System\Core.lua:158>

Locals: errorMessage = "...\Rotations\Shaman\Enhancement\EnhancementCuteOne.lua:428: attempt to call global 'hasLust' (a nil value)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:187
MESSAGE_TYPE_ERROR = 0

**Comment by CuteOne** [comment]
Fix has been pushed, thanks
