### ISSUE TITLE
Unholy DK (Outbreak)

### ISSUE THREAD

**Issue by darhanger** [CuteOne/BadRotations#155]
For some reason, in raids and dungeons, as well as on some bosses, it does not always use Outbreak. The same situation exists in PvP

**Comment by CuteOne** [comment]
Unholy still needs updating for Patch 7.2.5

**Comment by lemonlust** [comment]
Ill work on it

**Comment by zitnik1ng** [comment]
need rotation for talents 3/2/1/1/3/1/1 :/ GL

**Comment by kuukuukuatchu** [comment]
Closing due to age and multiple updates since this was posted.  Please reopen if still an issue.
