### ISSUE TITLE
Blood DK

### ISSUE THREAD

**Issue by darhanger** [CuteOne/BadRotations#156]
`Message: ...\AddOns\BadRotations\System\UI\Elements\Checkbox.lua:10: attempt to get length of field 'children' (a nil value)
Time: 06/29/17 11:27:59
Count: 2
Stack: ...\AddOns\BadRotations\System\UI\Elements\Checkbox.lua:10: attempt to get length of field 'children' (a nil value)Interface\SharedXML\SharedBasicControls.lua:204: in function <Interface\SharedXML\SharedBasicControls.lua:203>
[C]: ?
...\AddOns\BadRotations\System\UI\Elements\Checkbox.lua:10: in function `createCheckbox'
...ations\Rotations\Death Knight\Blood\BloodCuteOne.lua:72: in function `?'
...Ons\BadRotations\System\UI\Elements\PageDropdown.lua:26: in function <...Ons\BadRotations\System\UI\Elements\PageDropdown.lua:21>
(tail call): ?
...BadRotations\Libs\DiesalGUI-1.0\Objects\Dropdown.lua:176: in function `SetValue'
...Ons\BadRotations\System\UI\Elements\PageDropdown.lua:34: in function `createPagesDropdown'
Interface\AddOns\BadRotations\Rotations\cBuilder.lua:625: in function `createOptions'
Interface\AddOns\BadRotations\System\Core.lua:203: in function <Interface\AddOns\BadRotations\System\Core.lua:160>

Locals: errorMessage = "...\AddOns\BadRotations\System\UI\Elements\Checkbox.lua:10: attempt to get length of field 'children' (a nil value)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:187
MESSAGE_TYPE_ERROR = 0
`

**Comment by kuukuukuatchu** [comment]
Closing as issue resolved in discord. Please reopen if still an issue
