### ISSUE TITLE
libDraw works  incorrect

### ISSUE THREAD

**Issue by Toto233** [CuteOne/BadRotations#181]
![image](https://user-images.githubusercontent.com/536706/28054188-8f89183e-6646-11e7-94d4-272bf598b3c9.png)
When I draw a line it gives me a rectangle。does someone have the same question

**Comment by Toto233** [comment]
![forum](https://user-images.githubusercontent.com/536706/28054266-d37641f2-6646-11e7-805d-f6de67c4ab96.png)
It looks like this before

**Comment by Toto233** [comment]
local playerX, playerY, playerZ = GetObjectPosition("player",true)
local LibDraw = LibStub("LibDraw-1.0")
local showLines=true
LibDraw.clearCanvas()


local width=10
local length=20
local facing = GetObjectFacing("player")

if playerX~=nil and playerY~=nil and playerZ ~=nil then
    -- Near Left
    local nlX, nlY, nlZ = GetPositionFromPosition(playerX, playerY, playerZ, width/2, facing + math.rad(90), 0)
    -- Near Right
    local nrX, nrY, nrZ = GetPositionFromPosition(playerX, playerY, playerZ, width/2, facing + math.rad(270), 0)
    -- Far Left
    local flX, flY, flZ = GetPositionFromPosition(nlX, nlY, nlZ, length, facing + math.rad(0), 0)
    -- Far Right
    local frX, frY, frZ = GetPositionFromPosition(nrX, nrY, nrZ, length, facing + math.rad(0), 0)


    if showLines then
        -- Near Left
        LibDraw.Line(nlX, nlY, nlZ, playerX, playerY, playerZ)
        -- Near Right
        LibDraw.Line(nrX, nrY, nrZ, playerX, playerY, playerZ)
        -- Far Left
        LibDraw.Line(flX, flY, flZ, nlX, nlY, nlZ)
        -- Far Right
        LibDraw.Line(frX, frY, frZ, nrX, nrY, nrZ)
        -- Box Complete
        LibDraw.Line(frX, frY, frZ, flX, flY, flZ)
        LibDraw.Arc(playerX, playerY, playerZ+1, 15, 90, facing)
        LibDraw.Arc(playerX, playerY, playerZ+1, 22, 90, facing)

        LibDraw.Circle(playerX, playerY, playerZ+1,5)
    end

end

**Comment by kuukuukuatchu** [comment]
Ya it's broken.  Has been for a bit now.

**Comment by Toto233** [comment]
cool,It works
