### ISSUE TITLE
Huge lag since the last update?

### ISSUE THREAD

**Issue by Neretil** [CuteOne/BadRotations#184]
Hi

I updated the bot last night and since that i have huge lag effect when i turn it on. My fps/latency is fine, but the game starts to act as if im playing with 5 fps. Don't have any error messages, happening on my feral drood and as soon as i turn it off the lag is gone and as soon as i turn it on it's back.

Edit: Reinstalled the old version and everything works fine

Ps:
During the Desolate Host fight the bot can't use Regrowth, it stucks on the mouse coursor and have to click manually on myself

**Comment by kuukuukuatchu** [comment]
Issues resolved in patches since issues was opened.  Please reopen if still having problems or come to discord for troubleshooting.
