### ISSUE TITLE
soul barrier

### ISSUE THREAD

**Issue by Superkillen** [CuteOne/BadRotations#189]
hi!
I wonder if you could add soul barrier to the Vengence Demon hunter rotation :D

**Comment by bfwlegend** [comment]
I kinda dropped the Vengeance rotation due to lack of time irl, if I get time I'll add it, if not another dev could add it pretty fast, but may I ask why you're using soul barrier in pve?

**Comment by Superkillen** [comment]
feels like I am getting the most of that talent, saved me many many times since absorb doesn't affect healing reduced debuffs.
980k absorb + 623k heal with 5 soul fragments for 30 pain is kinda sweet tbh 💃 could probably pop it up even more if you snapshot the soulbarrier with some proccs

**Comment by CuteOne** [comment]
Vengeance rotation was recently updated, is this still needing addressed?

**Comment by bfwlegend** [comment]
Yeah, still need to add the new apl and add a few skills I didn't add while I was leveling

**Comment by CuteOne** [comment]
Sorry it took so long I ended up just writing my own, try out CuteOne profile for Vengeance and let me know how it goes.

**Comment by SvsGit** [comment]
Tested. Working fine.
