### ISSUE TITLE
Priest Not Working

### ISSUE THREAD

**Issue by leaderquebec** [CuteOne/BadRotations#2]
..\AddOns\BadRotations\Rotations\cBuilder.lua line 364:
   IsHelpfulSpell(): Invalid spell slot
Debug:
   [C]: IsHelpfulSpell()
   BadRotations\Rotations\cBuilder.lua:364: ?()
   BadRotations\Rotations\cBuilder.lua:411: cBuilder()
   BadRotations\Rotations\cBuilder.lua:77: update()
   BadRotations\System\Core.lua:136:
      BadRotations\System\Core.lua:67

Not working at all

**Comment by darhanger** [comment]
Shadow Priest not working. After start, just drop fps

**Comment by CuteOne** [comment]
wish i had a Priest to investigate this

**Comment by grutamu** [comment]
I no longer have a priest to look in to this issue :-/
