### ISSUE TITLE
Subtlet issues with EWT

### ISSUE THREAD

**Issue by darhanger** [CuteOne/BadRotations#201]
When turn on BR ingame fps dropped half. With others, there is no such problem

**Comment by CuteOne** [comment]
Just subtlety rogue?

**Comment by darhanger** [comment]
Just rogue all cpec. My fault, I forgot to include auto delay. But in other classes work without this function

**Comment by kuukuukuatchu** [comment]
Closing issue as resolved. Please reopen if still an issue.
