### ISSUE TITLE
How its work on 7.3? 

### ISSUE THREAD

**Issue by darhanger** [CuteOne/BadRotations#202]
I heard that the Blizzard сompletely broke EWT, FH, etc. What to do next? Do you have any news?

**Comment by LSharpAura** [comment]
FH admin says roughly two weeks after 7.3 comes out he should have FH working with the new obfuscation. Haven't seen anything about the other 2 unlockers. Just going to have to wait and see but likely going to be a decent delay before things are up and running again for unlockers.

**Comment by darhanger** [comment]
And what did they do? Some tweak in the code? Or is it something at the client's level?

**Comment by LSharpAura** [comment]
That would be a question to ask the devs of the unlocker as br has nothing to do with it.
