### ISSUE TITLE
beastmaster cuteone misdirection not working

### ISSUE THREAD

**Issue by ohmyivan** [CuteOne/BadRotations#203]
beastmaster cuteone   auto misdirection function not working

**Comment by CuteOne** [comment]
Added

**Comment by mujw** [comment]
still not work for me .  misdirection will not cast

**Comment by CuteOne** [comment]
Did you update, also did you enable the misdirection toggle?

**Comment by kuukuukuatchu** [comment]
Closing due to lack of response and age.  Please reopen if issue persists.
