### ISSUE TITLE
DK/Hunter Pet attack UI errors display

### ISSUE THREAD

**Issue by Aeliniak** [CuteOne/BadRotations#204]
I can not find the mistake.

**Comment by Aeliniak** [comment]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'BadRotations' tried to call the protected function 'PetAssistMode()'.
[C]: in function `PetAssistMode'
...Rotations\Rotations\Death Knight\Unholy\THUnholy.lua:642: in function `actionList_PetManagement'
...Rotations\Rotations\Death Knight\Unholy\THUnholy.lua:1097: in function `run'
BadRotations\Rotations\cCharacter.lua:238: in function `startRotation'
BadRotations\Rotations\cBuilder.lua:324: in function `update'
BadRotations\System\Core.lua:187: in function <BadRotations\System\Core.lua:124>

[C]: in function `SecureCall'
[string "Lua Unlock.lua"]:4: in function `AttackTarget'
[string "ATTACKTARGET"]:1: in function <[string "ATTACKTARGET"]:1>

**Comment by LSharpAura** [comment]
Protected function errors are unlocker issues due to the 7.3 update. Once the unlocker is working the error will stop. Closing as not a BR issue.
