### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by darhanger** [CuteOne/BadRotations#205]
Message: ...erface\AddOns\BadRotations\System\Functions\Unit.lua:7: attempt to call global 'ObjectIsVisible' (a nil value)
Time: 09/03/17 09:04:41
Count: 1
Stack: ...erface\AddOns\BadRotations\System\Functions\Unit.lua:7: attempt to call global 'ObjectIsVisible' (a nil value)
[C]: in function `ObjectIsVisible'
...erface\AddOns\BadRotations\System\Functions\Unit.lua:7: in function `GetObjectExists'
...erface\AddOns\BadRotations\System\Functions\Unit.lua:185: in function `getHP'
...terface\AddOns\BadRotations\Rotations\cCharacter.lua:157: in function `getCharacterInfo'
...terface\AddOns\BadRotations\Rotations\cCharacter.lua:105: in function `baseUpdate'
Interface\AddOns\BadRotations\Rotations\cBuilder.lua:319: in function `update'
Interface\AddOns\BadRotations\System\Core.lua:183: in function <Interface\AddOns\BadRotations\System\Core.lua:124>

Locals:

**Comment by kuukuukuatchu** [comment]
Resolved in updates since this was posted.  Please reopen if still an issue.
