### ISSUE TITLE
Beast Mastery/General editing question.

### ISSUE THREAD

**Issue by blackcardi** [CuteOne/BadRotations#206]
Is it possible to manually edit the Beast Mastery hunter rotation to pool focus before using Bestial Wrath? Also, to only use Aspect of the wild with 10 seconds or so remaining of the Bestial Wrath buff? I used to be able to edit my own profiles for my last CR, but it does not seem to be compatible with the latest version of FH and is no longer supported. I am yet unfamiliar with the "wording?" of Bad Rotations.

**Comment by CuteOne** [comment]
You can still edit, nothing stopping you from that. As far as me doing any changes I am trying to hold off until we have at least 1 stable unlocker to prevent confusion between BR issues and unlocker issues.

**Comment by CuteOne** [comment]
Closed due to age.
