### ISSUE TITLE
Feral Druid - Incarnation

### ISSUE THREAD

**Issue by Neretil** [CuteOne/BadRotations#207]
Hai CuteOne!

Could you add a "Don't use Prowl during Incarnation" option please? It's awesome in current raids, but makes mobs/bosses reset while soloing, especially when im doing old raids.

Thanks!

**Comment by CuteOne** [comment]
This will be fixed

**Comment by CuteOne** [comment]
Should be fixed now

**Comment by Neretil** [comment]
Thank you
