### ISSUE TITLE
How to display the BR Configration dialog?

### ISSUE THREAD

**Issue by zy4944796** [CuteOne/BadRotations#209]
If I close the BR Configration dialog,I can not open it again.
I typed the "/br Configration" ,but it is wrong command.So I tryed typing "/br help"  but I didn't find any marco about it .
Is there a handbook about it?

**Comment by CuteOne** [comment]
Mouse over the minimap icon it will explain (Little Fire Icon)

**Comment by zy4944796** [comment]
@CuteOne  There is not a icon in the screen ,if I attach the lua unlocker .

**Comment by CuteOne** [comment]
it could be behind another icon (known issue)

**Comment by CuteOne** [comment]
![image](https://user-images.githubusercontent.com/5498251/30244446-eb845008-958b-11e7-8236-81b51bd1127a.png)

**Comment by zy4944796** [comment]
@CuteOne So,How to fix this problem?How to find it .I disabled all addons except br,but it does not work on.

**Comment by CuteOne** [comment]
Not sure, if BR is present and unlocked that minimap icon will be present

**Comment by zy4944796** [comment]
@CuteOne  Thank you sir,I found it .Thank you .
I disabled all of addons except br and changed my resolution ratio,then I saw the fire icon on the top right screen.

**Comment by CuteOne** [comment]
Not a sir for the record :P
