### ISSUE TITLE
Lua error while flying, zoning into Elwyn forest from duskwood

### ISSUE THREAD

**Issue by bryan5989** [CuteOne/BadRotations#210]
Unable to copy the rest of message:

Message: attempt to concatenate a nil value
Time: 09/10/17 21:47:53
Count: 1
Stack: attempt to concatenate a nil value
[C]: ?
[C]: in function `IsHelpfulSpell'
...rface\AddOns\BadRotations\System\Functions\Spell.lua:211: in function `getSpellType'
Interface\AddOns\BadRotations\Rotations\cBuilder.lua:246: in function `?'
Interface\AddOns\BadRotations\Rotations\cBuilder.lua:479: in function `cBuilder'
Interface\AddOns\BadRotations\Rotations\cBuilder.lua:343: in function `update'
Interface\AddOns\BadRotations\System\Core.lua:187: in function <Interface\AddOns\BadRotations\System\Core.lua:124>

Locals:

**Comment by CuteOne** [comment]
the locals might be helpful (the lower part of message) if you can give that.

**Comment by bryan5989** [comment]
I didnt have swatter running at the time, so wasnt able to copy the full error. Will attempt to reproduce. do you know if lua errors are logged anywhere if you dont have an error catcher running?

**Comment by CuteOne** [comment]
I dont

**Comment by bryan5989** [comment]
I reproduced the error, this time zoning into northrend/Valiance Keep: It may be a different error, i just updated a few minutes ago.

Date: 2017-09-14 21:08:51
ID: 1
Error occured in: Global
Count: 1
Message: [string "Object Calls.lua"] line 136:
   Usage: UnitIsUnit("unit", "otherUnit")
Debug:
   [C]: ObjectCall()
   [string "Object Calls.lua"]:136: UnitIsUnit()
   ...AddOns\BadRotations\System\Engines\EnemiesEngine.lua:219:
      ...AddOns\BadRotations\System\Engines\EnemiesEngine.lua:180
   (tail call): ?
   BadRotations\Rotations\cBuilder.lua:283: ?()
   BadRotations\Rotations\cBuilder.lua:493: cBuilder()
   BadRotations\Rotations\cBuilder.lua:357: update()
   BadRotations\System\Core.lua:198:
      BadRotations\System\Core.lua:139
Locals:
(*temporary) = "Usage: UnitIsUnit("unit", "otherUnit")"

AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  Babylonian, v5.1.DEV.332(/embedded)
  BadRotations, v1.16.0
  BagBrother, v
  Bagnon, v7.3.2
  Configator, v5.1.DEV.406(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  DynastyCore, v9
  Informant, v7.4.5714 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.423(/embedded)
  Simulationcraft, v1.8.1
  Stubby, v7.4.5714 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  TomTom, vv70200-1.0.0
  ZygorGuidesViewer, v6.1
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=1fe)

**Comment by bryan5989** [comment]
seems ok
