### ISSUE TITLE
In UnholyLemon.lua's line 1130,the" cast.darkTransformation()" doesn't work fine.

### ISSUE THREAD

**Issue by zy4944796** [CuteOne/BadRotations#211]
My class is the Unholy DeathKnight,and I fournd the darktransformation doesn't cast automatically.
So I have read the code in UnholyLemon.lua,and I tryed to fix this problem,but I failed.
This is my code,
           -- if isChecked(colorGreen.."Dark Transformation") and not hasEquiped(137075) and rune <= 3 then
           --     if cast.darkTransformation() then return end
           -- end
            
           -- if isChecked(colorGreen.."Dark Transformation") and not hasEquiped(137075) then
                if cast.darkTransformation() then return end
           -- end

I have  reduced the conditions of casting darktransformation,but it hasn't worked yet.
I can't find the define of cast.darkTransformation(),so I don't find where the problem is.
Anyone can help me to fix this problem?

**Comment by kuukuukuatchu** [comment]
Just tested this on my DK and Abomination was transformed fine on dummy.  Is this still an issue?

**Comment by kuukuukuatchu** [comment]
Closing due to no response in 2 months. Please reopen if issue persists.
