### ISSUE TITLE
Maybe niche case...

### ISSUE THREAD

**Issue by bryan5989** [CuteOne/BadRotations#213]
In Borean Tundra, on quest Finding the Phylactery: There's a bit where you mount on a horse that takes you for a 300yd ride, through some mobs that aggro but you can't actually fight until the transport ends and you dismount. The ride is scripted, there's not player control. I popped the following error:

Date: 2017-09-17 21:23:33
ID: 1
Error occured in: AddOn: BadRotations
Count: 1
Message: Note: AddOn BadRotations attempted to call a protected function (TargetFrame:Show()) during combat lockdown.
Debug:
   [C]: Show()
   ..\FrameXML\TargetFrame.lua:111: TargetFrame_Update()
   ..\FrameXML\TargetFrame.lua:160: OnEvent()
   ..\FrameXML\UnitFrame.lua:921:
      ..\FrameXML\UnitFrame.lua:919
Locals:
None
AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  Babylonian, v5.1.DEV.332(/embedded)
  BadRotations, v1.16.0
  BagBrother, v
  Bagnon, v7.3.2
  Configator, v5.1.DEV.406(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  DynastyBooster, v16
  DynastyBoosterAlliance, v809
  DynastyBoosterHorde, v807
  DynastyCore, v9
  Informant, v7.4.5714 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.423(/embedded)
  Simulationcraft, v1.8.3
  Stubby, v7.4.5714 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  TomTom, vv70200-1.0.0
  ZygorGuidesViewer, v6.1
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=24f)

**Comment by kuukuukuatchu** [comment]
Protected function errors are normally unlocker related atm.  If issue persists once unlockers are all stable and fully functional again, please reopen issue.
