### ISSUE TITLE
Ret Paladin 7.1.5

### ISSUE THREAD

**Issue by itzjaayman** [CuteOne/BadRotations#22]
As of the patch going live today ret paladin does not seem to be working

**Comment by CuteOne** [comment]
This should at least be functional again, still need to review the APL for improvements.

**Comment by itzjaayman** [comment]
Just tried the fix working perfect cant wait for any improvements still to come thank you for quick response :)

**Comment by CuteOne** [comment]
I try my best :)

**Comment by PapkaZol** [comment]
At RU client does not work (

**Comment by CuteOne** [comment]
If there is any error message or anything you can tell me that can help me track down why this is the case then maybe I can fix it but as of right now I don't have a clue why it doesn't work.

**Comment by PapkaZol** [comment]
And how can I find out what error? It is necessary to install any addon?

**Comment by CuteOne** [comment]
I use BugSack and BugGrabber to error catching and reporting.

**Comment by PapkaZol** [comment]
147x ...faceBadRotations\System\GeneralFunctions.lua:186: Usage: UnitBuff("unit", [index] or ["name", "rank"][, "filter"])
[C]: in function `UnitBuff'
...faceBadRotations\System\GeneralFunctions.lua:186: in function `UnitBuffID'
BadRotations\Rotations\cBuilder.lua:202: in function `cBuilder'
BadRotations\Rotations\cBuilder.lua:77: in function `update'
BadRotations\System\Core.lua:136: in function <BadRotations\System\Core.lua:67>

Locals:
(*temporary) = "player"
(*temporary) = nil

**Comment by CuteOne** [comment]
When did you last update the bot files? I recently updated Retribution that resolved the buff errors.

**Comment by PapkaZol** [comment]
Updated 6:00 back. Right now I'll try to update again.

**Comment by CuteOne** [comment]
Yea my update was 6hrs ago on Ret

**Comment by PapkaZol** [comment]
Just updated again. All the same does not work (

**Comment by CuteOne** [comment]
Are you able to make screenshots?

**Comment by PapkaZol** [comment]
Right now I cleaned the WTF folder and earn! Sorry for the false alarm. But before the update really is not anything to work. Once again, thank you very much. For many years, I play WOW only thanks to you)

**Comment by CuteOne** [comment]
It's working now I take it? If so I am glad and thank you for your support.

**Comment by PapkaZol** [comment]
Yes, right now, everything is working. I restart the game and once again checked. Thank you!

**Comment by PapkaZol** [comment]
And when we can expect the use of "Execution Sentence" in rotation?  Thanks for the answer!

**Comment by CuteOne** [comment]
I will see what I can do about APL update for logic changes tonight, tomorrow at the latest. That said there is logic already present for use of Execution Sentence.

**Comment by PapkaZol** [comment]
We look forward to!) Thank you very much for your efforts!

**Comment by PapkaZol** [comment]
251x ...Rotations\Paladin\Retribution\RetributionCuteOne.lua:190: attempt to index global 'units' (a nil value)
...Rotations\Paladin\Retribution\RetributionCuteOne.lua:190: in function `run'
BadRotations\Rotations\cCharacter.lua:292: in function `startRotation'
BadRotations\Rotations\cBuilder.lua:81: in function `update'
BadRotations\System\Core.lua:139: in function <BadRotations\System\Core.lua:67>

Locals:
artifact = <table> {
 ashbringersLight = false
 echoOfTheHighlord = false
 righteousBlade = true
 sharpenedEdge = true
 wrathOfTheAshbringer = true
 highlordsJudgment = true
 bladeOfLight = true
 protectorOfTheAshenBlade = true
 deliverTheJustice = true
 embraceTheLight = false
 mightOfTheTemplar = false
 artificialStamina = false
 healingStorm = false
 artificialDamage = false
 wakeOfAshes = true
 ashesToAshes = true
 unbreakableWill = true
 divineTempest = false
 endlessResolve = false
 deflection = false
 rank = <table> {
 }
}
buff = <table> {
 crusade = <table> {
 }
 netherwinds = <table> {
 }
 whisperOfTheNathrezim = <table> {
 }
 bloodlust = <table> {
 }
 theFiresOfJustice = <table> {
 }
 timeWarp = <table> {
 }
 divinePurpose = <table> {
 }
 ancientHysteria = <table> {
 }
 shadowmeld = <table> {
 }
 greaterBlessingOfWisdom = <table> {
 }
 heroism = <table> {
 }
 greaterBlessingOfKings = <table> {
 }
}
cast = <table> {
 crusaderStrike = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 greaterBlessingOfWisdom = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 divineHammer = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 contemplation = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 eyeForAnEye = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 blindingLight = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 quakingPalm = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 greaterBlessingOfKings = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 global = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 rebuke = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 shieldOfVengeance = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 hammerOfJustice = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 repentance = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 wordOfGlory = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 giftOfTheNaaru = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 holyWrath = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 judgment = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 blessingOfProtection = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 bladeOfJustice = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 divineShield = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 shadowmeld = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 templarsVerdict = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 crusade = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 zeal = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 wakeOfAshes = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 debug = <table> {
 }
 tyrsDeliverance = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 blessingOfFreedom = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 handOfHinderance = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 avengingWrath = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 layOnHands = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 judgmentOfLight = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 redemption = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 flashOfLight = <function> defined @BadRotations\Rotations\cBuilder.lua:350
 handOfReckoning = <function> defined @Interf

**Comment by PapkaZol** [comment]
Does not work(

**Comment by CuteOne** [comment]
Fixed, sorry about that.

**Comment by PapkaZol** [comment]
Thank you very much for the correction. Now everything is working. No errors. But I noticed that the Execution Sentence works not on cooldown. Sometimes it is not used for a long time. At the beginning of the fight running. And then ceases.

**Comment by CuteOne** [comment]
there is a time to die check on it to where it wont cast it unless the target will live to take the damage from it, this could be the cause

**Comment by itzjaayman** [comment]
When i have cooldowns set to "on" i only get judgement and auto attack
also when set to auto its working fine with multiple targets but on single target fights again only judgement and auto attack are working

**Comment by CuteOne** [comment]
This is not the behavior im getting on my level 77 pally, everything is
working fine for me.

**Comment by itzjaayman** [comment]
sorry thought i deleted that not sure why it started to happen but its working again after /reload
