### ISSUE TITLE
SlashCommands "/br pause hold" macro doesn't work

### ISSUE THREAD

**Issue by zekaey** [CuteOne/BadRotations#222]
"BadRotations/System/SlashCommands.lua"

So i noticed that "/br pause toggle" macro works but the "/br pause hold" just doesn't seem to work.

Any way of making "hold" macro work?

**Comment by CuteOne** [comment]
Hold is as it describes, you have to hold it to keep it paused.

**Comment by zekaey** [comment]
The thing is it is actually deactivated in every single slashcommands.lua . 

I did activate it by removing extra "--[[]]--" but it just doesn't work. Is there a reason why it hasn't been activated in a raw file as you can see here in bold?

function slashHelpList()
	SLASH_BR1, SLASH_BR2 = '/br', '/badrotations'
	SlashCommandHelp("br","Toggles BadRotations On/Off")
	SlashCommandHelp("br help","Displays this list of help commands. ***Obviously***")
	SlashCommandHelp("br blacklist","Adds/Removes mouseover unit to healing blacklist.")
	SlashCommandHelp("br blacklist dump","Prints all units currently on blacklist.")
	SlashCommandHelp("br blacklist clear","Clears the blacklist.")
	**-- SlashCommandHelp("br pause hold","Pauses while held (via macro).")**
	SlashCommandHelp("br pause toggle","Switches Pause On/Off")
	SlashCommandHelp("br queue clear","Clears the Spell Queue of all queued spells.")
	SlashCommandHelp("br queue add spellId","Adds the Spell to the Queue by Spell Id.")
	SlashCommandHelp("br queue remove spellId","Removes the Spell from the Queue by Spell Id.")
	SlashCommandHelp("br updaterate", "Displays Current Update Rate")
	if select(2, UnitClass("player")) == "HUNTER" then
		SlashCommandHelp("br disengage", "Assign to macro to Forward Disengage.")
	end
end

**Comment by LSharpAura** [comment]
That's not activating it. Thats literally just adding that line of text to the help file that comes up when you type /br help

**Comment by zekaey** [comment]
so how do i activate the "/br pause hold" macro then? I tried tempering with this code by removing bu removing unnecessary "[[]]---" characters but yet still it doesnt work when i hold a macro "/br pause hold"

-- Pause
	elseif msg1 == "pause" then
		--[[if msg2 == "hold" then
			ChatOverlay("Profile Paused")
			return true
		else]]if msg2 == "toggle" then
			if br.data.settings[br.selectedSpec].toggles['Pause'] == 0 then
				ChatOverlay("\124cFFED0000 -- Paused -- ")
				Print("|cFFFF0000Paused")
				br.data.settings[br.selectedSpec].toggles['Pause'] = 1
			else
				ChatOverlay("\124cFF3BB0FF -- Pause Removed -- ")
				Print("|cFF3BB0FFPause Removed")
				br.data.settings[br.selectedSpec].toggles['Pause'] = 0
			end
		else
			Print("Invalid Option for: |cFFFF0000"..msg1.."|r try "..--[["|cffFFDD11 /br pause hold |r - Pauses while held (via macro) or ]]"|cffFFDD11 /br pause toggle |r - Switches Pause On/Off")
		end

**Comment by CuteOne** [comment]
I dont remember when that was commented out but there is a hold pause function available by default, if you change the pause toggle in the profile specific options then you can do it by the hot key or by left alt (default on none)

**Comment by CuteOne** [comment]
Looked through commit history and its been disabled since before December 2016, once I am able to I will be glad to look to getting it working but in the mean time that default functionality should work fine.

**Comment by zekaey** [comment]
Oh i am aware of the hold hot key"shift,ctr,alt,etc...." 

But i was more curious about a macro that pauses the rotation for lets say 0.3 sec everytime you push on it in order to force activate your other macro. 
For instance:  

"/br pause hold
/cast Life Cocoon"

Surely it can be achieved by holding one of the pause hotkeys and pressing your Cocoon macro. But it is way more efficient if that can be achieved by pressing only one key.

**Comment by CuteOne** [comment]
you can queue up life cocoon via the slash commands which will cast it at the next available cast point.

**Comment by zekaey** [comment]
what about a bear form? if I que up a bear form by pressing a queue up macro many times does it mean it will cast bear form the amount of times you pressed the macro?

**Comment by zekaey** [comment]
/br queue doesn't work right after the GCD. It cast the necessary  druid hots on you first and after all of it done only then the queue of the bearform is performed :(

**Comment by CuteOne** [comment]
yea any spell added is added to the end of the queue

**Comment by kuukuukuatchu** [comment]
This has been essentially negated by the new key pause system allowing you to manually cast a spell by pausing rotation so I am closing.  If there is a still a problem, please re-open.

**Comment by zekaey** [comment]
So how do I pause rotation now to spam an ability with one key that I need urgently? /br pause macro doesn't work.
