### ISSUE TITLE
Ww monk

### ISSUE THREAD

**Issue by Slyguyy** [CuteOne/BadRotations#228]
Anyone else having troubles where when/after ww uses fists of fury char gets bugged and just keep either running sideways or turning around in circle. I don't find it happening in instance so far but a lot in open world

**Comment by Slyguyy** [comment]
Might have something to do with always facing turned on fh settings. I'll do some more testing

**Comment by CuteOne** [comment]
That is a known issue with FH.

**Comment by Slyguyy** [comment]
So is that just a general thing that happens or is it to do with the always facing option. Only happens when casts fist of fury

**Comment by CuteOne** [comment]
It's a thing with FH and the Always Facing option.

**Comment by Slyguyy** [comment]
Ok ty 😀
