### ISSUE TITLE
Not work mage and priest.

### ISSUE THREAD

**Issue by PapkaZol** [CuteOne/BadRotations#23]
Both give similar error. In general, do not run.

31x ...s\BadRotations\Rotations\Mage\Frost\FrostCuteOne.lua:478: attempt to call global 'actionList_Cooldowns' (a nil value)
...s\BadRotations\Rotations\Mage\Frost\FrostCuteOne.lua:478: in function `run'
BadRotations\Rotations\cCharacter.lua:292: in function `startRotation'
BadRotations\Rotations\cBuilder.lua:81: in function `update'
BadRotations\System\Core.lua:139: in function <BadRotations\System\Core.lua:67>

Locals:

145x BadRotations\Rotations\cBuilder.lua:355: IsHelpfulSpell(): Invalid spell slot
[C]: in function `IsHelpfulSpell'
BadRotations\Rotations\cBuilder.lua:355: in function `?'
BadRotations\Rotations\cBuilder.lua:402: in function `cBuilder'
BadRotations\Rotations\cBuilder.lua:77: in function `update'
BadRotations\System\Core.lua:136: in function <BadRotations\System\Core.lua:67>

Locals:
(*temporary) = nil

**Comment by dbtftw** [comment]
For Frost mage try the latest Pull and the DBT APL

**Comment by PapkaZol** [comment]
I still do not understand why the mage problem and you get this error. As it is still possible to fix it? I have a Russian game client.

**Comment by PapkaZol** [comment]
Understood, mag works. Thanks for the tip)

**Comment by PapkaZol** [comment]
How do I delete spam in chat the magician? Constantly writing "on the move!"
