### ISSUE TITLE
Latency Tolerance Option [Suggestion]

### ISSUE THREAD

**Issue by TitoBR** [CuteOne/BadRotations#231]
Hey guys, wanted to suggest an option like 'Latency Tolerance' option in General should be added

currently cast function (cClassSpec.lua) is
getSpellCD(v) == 0

however with this BR doesn't queue spells to the server like a normal player... unless you're playing at <10 ms this is untimely a DPS because server ultimately won't return 0 until it's ready for you

so I changed it to 

getSpellCD(v) < getLatency()

and I gained nearly an extra GCD every 10 secs with my latency (80ms), very big DPS gain for me.. it works very well for melee classes

an option to turn this on & off would be nice should I don't have to change it when I update :]

**Comment by CuteOne** [comment]
Worth looking into.

**Comment by CuteOne** [comment]
Added to the getSpellCD function
