### ISSUE TITLE
Cast Heroic Leap, 10 yards no target DIRECTLY BEHIND PLAYER [HELP/REQUEST]

### ISSUE THREAD

**Issue by TitoBR** [CuteOne/BadRotations#232]
Hey guys, working on a minmax arms script, trying to create a fancy function to cast Heroic Leap DIRECTLY BEHIND me so I can charge back in for max rage.

Essentially I'm trying to recreate:
actions.single+=/heroic_charge,if=rage.deficit>=40&(!cooldown.heroic_leap.remains|swing.mh.remains>1.2)

I have great charge/auto movement logic, but I can't get a working Heroic Leap.

Something like this I guess:
cast.heroicLeap(8yards.180angle,"ground")

I think having a method to use a ground cast at specific yard and angle would be useful!

I'm not really good at coding this stuff unless I have a reference so if anyone could help me out or point me to an example of this type of function in BR I'd be most grateful :]

will be releasing this arms rotation once I finished

**Comment by CuteOne** [comment]
All you would need is the X,Y,Z position i yards behind you...but converting your position to new position I am not entirely sure on how to do but it should certainly be possible.

**Comment by TitoBR** [comment]
TY! this works perfect

```
	--Heroic Leap for Charge--
	function heroicLeapCharge()
		local X, Y, Z = GetObjectPosition("player")
		CastSpellByName(GetSpellInfo(6544))
		ClickPosition(X-8,Y-8,Z)
	end
```

**Comment by CuteOne** [comment]
Typical, I was overthinking it

**Comment by TitoBR** [comment]
Nah JK, it's not that simple since X,Y,Z doesn't account with your facing position, so it will always be 8 yards, but not in the right direction unless you're facing west-north xD

I reckon gonna have to factor in angle and do some math to get it right

**Comment by CuteOne** [comment]
That's what I was thinking

**Comment by bfwlegend** [comment]
May want to use a trace line to make sure you can leap 8 yards behind you

**Comment by TitoBR** [comment]
kk sick thanks for the traceline tip... got it, was a nifty function in firehack's Math.ua to do exactly what I wanted ^_^

```
	--Heroic Leap for Charge--
	function heroicLeapCharge()
		local X, Y, Z = GetObjectPosition("player")
		local X2, Y2, Z2 = GetPositionFromPosition(X, Y, Z, -10, facing, 0)
		local facing = GetObjectFacing("player")
		local yards = -10
		if TraceLine (X, Y, Z, X2, Y2, Z2, 0x10, 0x100) == nil then
			CastSpellByName(GetSpellInfo(6544))
			ClickPosition(GetPositionFromPosition(X, Y, Z, yards, facing, 0))
		end
	end
```

now all I need is a swing timer function and it's golden

**Comment by TitoBR** [comment]
does anyone have a list of the HitFlags /bit.bor table for TraceLine? 

all I know is line of sight, I don't know 'No Path' or 'Out of Range' :/

**Comment by TitoBR** [comment]
nvm there's only 0x10... I thought there was more since traceline would return too often when clearly it was safe cast, but my problem seemed to be to add 2.25 to z axis ^^

```
	--Heroic Leap for Charge--
	function heroicLeapCharge()
		local X, Y, Z = GetObjectPosition("player")
		local face = GetObjectFacing("player")
		local X2, Y2, Z2 = GetPositionFromPosition(X, Y, Z, -10, face, 0)
		if TraceLine (X, Y, Z + 2.25, X2, Y2, Z2 + 2.25, 0x10) == nil then
			CastSpellByName(GetSpellInfo(6544))
			ClickPosition(GetPositionFromPosition(X, Y, Z, -10, face, 0))
		end
	end
```
and a macro test for traceline in game:

```
/run X, Y, Z = GetObjectPosition("player")
/run face = GetObjectFacing("player")
/run X2, Y2, Z2 = GetPositionFromPosition(X, Y, Z, -10, face, 0)
/dump TraceLine (X, Y, Z + 2.25, X2, Y2, Z2 + 2.25, 0x10)
```

anyway I'm done with this, it's 100% now so feel free to close issue

**Comment by TitoBR** [comment]
jk not perfect, need hit box compensation -_-

now you can chill in the middle of a large hitbox and still get the proper range for charge
```
	--Heroic Leap for Charge--
	function heroicLeapCharge()
		local X, Y, Z = GetObjectPosition("player")
		local face = GetObjectFacing("player")
		local hitBoxCompensation = UnitCombatReach('target') / GetDistanceBetweenObjects('player','target')
		local yards = -8.5 - hitBoxCompensation
		local X2, Y2, Z2 = GetPositionFromPosition(X, Y, Z, yards, face, 0)
		if TraceLine (X, Y, Z + 2.25, X2, Y2, Z2 + 2.25, 0x10) == nil then
			CastSpellByName(GetSpellInfo(6544))
			ClickPosition(X2,Y2,Z2)
		end
	end
```

**Comment by CuteOne** [comment]
I have this mostly incorporated into ArmsCuteOne, closing.
