### ISSUE TITLE
Swing Timer [ADDITION]

### ISSUE THREAD

**Issue by TitoBR** [CuteOne/BadRotations#234]
finally made a working swing timer for arms warrior

```
	---------------------
	--[[ Swing Timer ]]--
	if param == "SWING_DAMAGE" then
		swingTimer = 0
		lastMH = GetTime()
		nextMH = lastMH + UnitAttackSpeed('player')
	end
	
	if swingTimer then
		swingTimer = nextMH - GetTime()
	end
```

requesting this gets added to combatlog.lua ^^

**Comment by CuteOne** [comment]
Will be in the next push

**Comment by TitoBR** [comment]
this actaully wasn't right, needed source == br.guid because in group it gets messed up

	if source == br.guid and param == "SWING_DAMAGE" then

**Comment by CuteOne** [comment]
Added the change in my copy, will be in the next update. (sounds like another canned response lol)
