### ISSUE TITLE
Druid Feral Combatlog 

### ISSUE THREAD

**Issue by MastaRage** [CuteOne/BadRotations#237]
24x ...aceBadRotations\System\readers\combatlog.lua:303: attempt to index field '?' (a nil value)
...aceBadRotations\System\readers\combatlog.lua:303: in function `Druid'
...aceBadRotations\System\readers\combatlog.lua:72: in function <...aceBadRotations\System\readers\combatlog.lua:43>

Locals:

**Comment by CuteOne** [comment]
Solved
