### ISSUE TITLE
Creating a macro for toggles

### ISSUE THREAD

**Issue by TitoBR** [CuteOne/BadRotations#238]
I made a custom toggle for my profile but I forgot the macro that will allow me to keybind it (I had one when I was using it as Badboy but lost it since)

Does anyone still have this macro / method to keybind your BadRotations toggles?

**Comment by CuteOne** [comment]
/brHelp will show you a list of slash commands you can do....any slash command can be added to a macro and keybound.

**Comment by TitoBR** [comment]
awesome, thanks
