### ISSUE TITLE
Frost/Blood DK

### ISSUE THREAD

**Issue by Evaldazz** [CuteOne/BadRotations#24]
Blood:
Rotation shouldnt be using Marrowrend to stack it up to +10 all the time, sometimes it caps and its a waste of resources.
Option to not use it after +6 would be nice.

Frost:
Not maintaining Icy Talons at 3 stacks with Frost Strike (huge dps loss)
Wasn't using Glacial Advance on 1 Target (was set to 1 in options)
Not using Howling Blast on Rime procs. Should cast even when mobs have Frost Fever on already.

**Comment by CuteOne** [comment]
To my knowledge Blood has not been updated for patch 7.1.5 as for Frost I just updated it based on the SimC here... https://github.com/simulationcraft/simc/blob/legion-dev/profiles/Tier19M/Death_Knight_Frost_T19M.simc

**Comment by Vilt-Coding** [comment]
For blood, what rotation are you using?

**Comment by CuteOne** [comment]
Frost DK APL has updated recently and I have updated the profile accordingly let me know if that is better.

**Comment by Evaldazz** [comment]
For Blood I use Vilt APL. Works realy good overall, just that one thing I noticed bugs me a bit.
Talents are: 3-1-1-2-1-3-3
Using Blooddrinker manually too.

For Frost, update didn't change anything. I am no programmer, but I think its there in the code, no idea why its not working.
Looks like its trying to keep the stacks up, but it falls so often. Tried switching gear around, to make sure its not because of my stats, same results with higher resource regeneration tho.
As for Howling Blast, still not casting on Rime procs. 

Thanks for looking into it.

**Comment by Vilt-Coding** [comment]
Stacking >= 6 is optimal when using Ossuary + Foul Bulwark, it shouldn't be overcapping unless the buff is about to fall off. If this isnt the case send me logs on discord or something. Blooddrinker is gonna get nerfed back into unviability, I'lll see if I can get around to adding it to the routine tho, need add proper soulgorge usage anyway.
