### ISSUE TITLE
Cast function issue and artifacts [BUG]

### ISSUE THREAD

**Issue by TitoBR** [CuteOne/BadRotations#242]
Newest update seems to bring issues with artifacts, at least on prot / arms warrior, they will not cast

This looks like an issue with 'amIinRange' as if I remove that check, the arms artifacts will have no problems

However on prot I couldn't get the artifact to work with cBuilder.lua cast function, and if you use your prot profile and set to anything besides 'Never' it will break the rotation.

This is using
if cast.warbreaker() then return true end
ect.

I think all artifacts that don't have a target requirement are having issues with the new cast function, maybe the reason the shadow priest is broken as well

maybe a custom cast function for artifacts?

**Comment by CuteOne** [comment]
Arms warrior is having a lot of changes being done, if Prot Artifact is like Arms then the fix is simple.

**Comment by CuteOne** [comment]
This should be fixed
