### ISSUE TITLE
Ret pally rotation - stuck on 5 holy power

### ISSUE THREAD

**Issue by dyser99** [CuteOne/BadRotations#245]
Not sure what is causing it, but the rotation stops randomly at 5 holy powers and just melees or continue to use holy power generator moves instead of finishers. This started happening after I updated to the latest version today.

Some errors that have popped up in game:

677x ...Rotations\Paladin\Retribution\RetributionCuteOne.lua:652: attempt to perform arithmetic on local 'holyPowerMax' (a nil value)
...Rotations\Paladin\Retribution\RetributionCuteOne.lua:652: in function `run'
BadRotations\Rotations\cCharacter.lua:292: in function `startRotation'
BadRotations\Rotations\cBuilder.lua:41: in function `update'
BadRotations\System\Core.lua:352: in function <BadRotations\System\Core.lua:260>

**Comment by dyser99** [comment]
After some more observations and messing with the settings, this issue seemed to be only happening if the artifact is on CD.

**Comment by CuteOne** [comment]
Latest commit solved the issue, the error report told me exactly what I needed.
