### ISSUE TITLE
Suggestion for Havoc Demonhunter for ultimate damage.

### ISSUE THREAD

**Issue by rollfacedk** [CuteOne/BadRotations#25]
Please priority Throw Glaive than Fel Rush for filler spells (if you have nothing to press). because Throw Glaves has more dps than Fel Rush especially when you have "Master of the Glaive' as a talent. thank you!

edit: Only use throw glaive and Fel Rush as a filler. but throw glaive is more priority than fel Rush

Priority throw glaive = single target
Priority fel rush - 3 or more targets

my talents are 222311

**Comment by CuteOne** [comment]
Is this still an issue?
