### ISSUE TITLE
Why don't you upgrade the roration of Death Knight to 8.0?

### ISSUE THREAD

**Issue by zy4944796** [CuteOne/BadRotations#250]
Why don't you upgrade the roration of Death Knight to 8.0? The last commiting is 9 months ago.

**Comment by CuteOne** [comment]
It's on the list.

**Comment by Vilt-Coding** [comment]
bik soon ™

**Comment by zy4944796** [comment]
@CuteOne Five days passed,could you update it quickly please? Every class has been updated to 8.0 except this.Is there a discrimination against the Death Knight?

**Comment by zy4944796** [comment]
@CuteOne Thank you for your quick reply and hark work,best regards.

**Comment by CuteOne** [comment]
I did nothing today but focus on Frost DK, it is now updated.
