### ISSUE TITLE
Distance to target

### ISSUE THREAD

**Issue by PapkaZol** [CuteOne/BadRotations#26]
How to increase the distance to the target to do damage? Often standing next to the target and the rotation does not work. A little bit closer come near or away, and begins to work. Although his hands at this moment could be beat. This problem in melee dd. Hopefully Google translator written clearly what I mean)

**Comment by Vilt-Coding** [comment]
Class/spec/talents?

**Comment by PapkaZol** [comment]
For example at the Paladin and dh. We must look for the right place that would have continued to work rotation. This loss of DPS. In this case, the hands can strike. Rotation stops working in close combat and long-range causes only damage on the target. Paladin Talents 2-1-3-2-2-1-2

**Comment by CuteOne** [comment]
I've played Havoc DH extensively and have not noticed any issues. :(

**Comment by PapkaZol** [comment]
Maybe it's because I have a Russian game client. BadRotations many functions do not work at the Russian game client. Probably this is one of them.

**Comment by CuteOne** [comment]
Is there any difference with using the English version?

**Comment by PapkaZol** [comment]
cooldowns and defensive functions are not all working on different characters. I have 6 characters lvl 110 and not at all everything works. On helii heroic heroes in melee badly beaten tentacles. You have to jump that would beat on him. Perhaps it is only in Russian client)

**Comment by CuteOne** [comment]
I know english isn't your language so I am trying to follow what you are saying but I can't exact;y te;; waht you are saying there.
