### ISSUE TITLE
AssassinationCuteOne.lua - Some Settings dont work & huge performance issues

### ISSUE THREAD

**Issue by tw88** [CuteOne/BadRotations#356]
some Settings like stealth 20m and auto poison do not work (poisons not applied) 

- there are some huge performance issues also, in LFR the fps drop from ~100 to under ~10 and it laggs to the point where the rotation hangs / dps are very low. 
This issue was gone after switching to Sublety (same raid / instance)

**Comment by CuteOne** [comment]
Aside from FPS this should be fixed now.

**Comment by tw88** [comment]
the fps drops seem to come from the auto-targeting

**Comment by CuteOne** [comment]
Which is weird as it doesn't really take the long to run.
