### ISSUE TITLE
Beastmaster

### ISSUE THREAD

**Issue by BiggieSmallsRIP** [CuteOne/BadRotations#357]
bestial wrath seems to be missing CD check. always casting in combat.

a murder of crows not being used of bestial wrath on cooldown. ( i think) something is blocking from casting it when it should. Like it casts when mob is about to die.

**Comment by fiskee** [comment]
Bestial Wrath should not be considered a cooldown, as with barbed shot you have a very low cd, so would be a waste to not use it on normal mobs.
Could consider making a button for it though, to make it disable usage outside CDs, if you are about to meet a boss, leaving issue open.

Amoc will only be used on thrash mobs if we are sure they will die before it runs out, to not trigger cooldown. On boss/with cds on it will be used on CD.

**Comment by kuukuukuatchu** [comment]
Closing as answer was provided.  Please re-open if needed.
