### ISSUE TITLE
Resto Druid not working fully.

### ISSUE THREAD

**Issue by TheRealZeagan** [CuteOne/BadRotations#361]
Hello there,

For some reason restro Druid is only casting Lifebloom on tank, and is only using regrowth when enabled "Keep Regrowth on Tank" and ignores all the % to cast options.

In combat log it only does following
Nature's Curse
Regrowth on tank when about to expire
Rebirth
Lifebloom
Barkskin

Is there a reason for this?

**Comment by LSharpAura** [comment]
Turn on healing engine would be my guess.

**Comment by TheRealZeagan** [comment]
It is on

**Comment by TheRealZeagan** [comment]
Worked after reload btw.
