### ISSUE TITLE
Assassin rogue problems

### ISSUE THREAD

**Issue by BiggieSmallsRIP** [CuteOne/BadRotations#372]
Not checking/using if we have poisons applied to the weapons.

Vendetta not being used at all. also you have  3 modes on toggles frame and 3 options in the menu, probably can remove one.  (99% sure its related to subterfuge talent)

Garrot + subterfuge talent is bugged.  From stealth, it will cast garrot but let it expire and never cast it again for the rest of the fight.
Right now it uses stealth> 2cp rapture>mutilate spam>envenom ( never casting garrot because of talent bug above)

also when subterfuge is fixed it's not optimal to use rapture opener from stealth with <3 combo points if we have "shrouded suffocation" trait imo.

**Comment by CuteOne** [comment]
Have you updated recently?

**Comment by CuteOne** [comment]
that's really strange as it was working fine in testing past 2 nights

**Comment by tw88** [comment]
i can confirm that poisons are not applied (latest version)

**Comment by CuteOne** [comment]
This should now be resolved, closing.
