### ISSUE TITLE
Frost DK Problems

### ISSUE THREAD

**Issue by H-mmer** [CuteOne/BadRotations#392]
Hi there!

Been trying out that Frost DK rotation but it seems there's something off with the Breath of Sindragosa. I've looked through the code and i really have no idea what's causing it. But the problem is that Breath of Sindragosa only stays active for about 5-9seconds (9,26s was by biggest). For some reason it _always_ uses Frost Strike on the rotation during breath of sindragosa ticking. Anyway you could look into this ? :)

**Comment by kuukuukuatchu** [comment]
A new profile has been made for Frost DK and people are reporting much better up time on BoS.  The old profile is being looked at to find any issues.  Please reopen this ticket if you continue to have problems.
