### ISSUE TITLE
disc error

### ISSUE THREAD

**Issue by novicane2** [CuteOne/BadRotations#394]
![wowscrnshot_100818_210159](https://user-images.githubusercontent.com/43975551/46641091-aebf0d00-cb3d-11e8-8a2d-d5501f5ebec1.jpg)
![wowscrnshot_100818_210208](https://user-images.githubusercontent.com/43975551/46641093-aebf0d00-cb3d-11e8-92a7-4000ec11f519.jpg)
![wowscrnshot_100818_210216](https://user-images.githubusercontent.com/43975551/46641094-aebf0d00-cb3d-11e8-99ba-766a9b3a02aa.jpg)

**Comment by LSharpAura** [comment]
First two can be ignored as they are being looked into by the unlocker dev. Third one Aura will need to look at.

**Comment by kuukuukuatchu** [comment]
Closing as problem has been resolved with updates.  Please re-open if issue persists.
