### ISSUE TITLE
how to enable/configure pokeconfiguration?

### ISSUE THREAD

**Issue by edgarskrauklis** [CuteOne/BadRotations#396]
how to enable pet battles? I can see rotations under misc, but no gui for that.

https://github.com/CuteOne/BadRotations/tree/master/System/Misc/PokeRotation

**Comment by LSharpAura** [comment]
Pet battles don't work.  Haven't for a long time.

**Comment by edgarskrauklis** [comment]
thank you.

**Comment by kuukuukuatchu** [comment]
Issue resolved.  Closing.
