### ISSUE TITLE
lua unlocker

### ISSUE THREAD

**Issue by PapkaZol** [CuteOne/BadRotations#399]
Hey. I wanted to ask. Which is better lua unlocker to use? firehack no longer works or i can't find new site. Tell me please. Sorry for such a question.

**Comment by bizkut** [comment]
Ewt

**Comment by PapkaZol** [comment]
They only pay Bitcoins. And I do not know how to pay them (There is nothing more?

**Comment by LSharpAura** [comment]
They have guides on their website how to pay with bitcoins.  BR also supports KFM and the information for it is posted in the announcements on discord.

**Comment by PapkaZol** [comment]
What is KFM? I could not find information about him in the discord. Please write a link.

**Comment by kuukuukuatchu** [comment]
As some of you may or may not be aware BR now works with KFM, this is an additional option for those who are unable to utilize EWT. That said like EWT, KFM does charge for unlocking and as such the cost associated is for that service; BR it self is free. 

That said here is the important information to know about KFM...
1) pricing: 29EUR/7 days, 59EUR/30 days, 128EUR/90 days and 299EUR/365 days (almost the same price compared to EWT subscription for a year with no hassle of BitCoins payment and extra fees)
2) where to buy KFM credits using PayPal: https://selly.gg/@GoHandsFree (everything needed will be sent by email instantly, including installation guides)
3) what KFM is: KFM is a Private platform with limited userbase which uses complex hardware-based technologies, has NO Injection or DLL Integration, NO Memory Editing, NO Standalone Process and NO Pixels or Key Simulation. Current limitations: Intel CPU PCs are supported only (AMD later next month)

**Comment by kuukuukuatchu** [comment]
Closing this as question has been answered.  Please reopen if needed.
