### ISSUE TITLE
FPS drop on AMD platform. 

### ISSUE THREAD

**Issue by darhanger** [CuteOne/BadRotations#4]
Use EWT + Bad Rotation at home and work. 
Work PC:
CPU - Intel Pentium G3258 3.7 GHz
GPU - GT 240
RAM - 8 GB.

Home PC:
CPU - AMD A6-3650 3.1 GHz
GPU - GTX 650 2GB
RAM -  8 GB. 

At work all fine, love FPS but it's all because of the GPU, but at home after on BadRotation FPS droped half + little freezes.

**Comment by leaderquebec** [comment]
CPU - FX-6300
GPU - R7-240
RAM - 4GB

No fps prob.

**Comment by Aleksaas** [comment]
I also noticed fps drop when turn on bad rotations. It drops to 10-15 from 40-50.

**Comment by Aleksaas** [comment]
But only on Nythendra which is strange...

**Comment by CuteOne** [comment]
This is one of the reasons why I am focusing more on rewriting now instead of trying to patch.

**Comment by gaodayihao** [comment]
I register event "COMBAT_LOG_EVENT_UNFILTERED" "NAME_PLATE_UNIT_ADDED" to handle the enmeies table instead of "ObjectCount()" "GetObjectWithIndex()", it seems to solve FPS issues.
@CuteOne  see these commit : f2914f3bd62aa60af0de20221c2dc95e6eb5bcb7   f8501034578631f553dfe50c881d713a8cd36f7c  d8605f05a86e84f3688995eb76442ae0de30b77c

**Comment by gaodayihao** [comment]
The code in FireHack\Scripts\Tracking.lua line 51.
```
AddTimerCallback(1,
	function ()
		for Index = 1, GetObjectCount() do
			local Object = GetObjectWithIndex(Index);
			if ObjectIsType(Object, ObjectTypes.Unit) or ObjectIsType(Object, ObjectTypes.GameObject) then
				local Tracked = false;

				for Name, Filter in pairs(Filters) do
					if Filter.Enabled and Filter.Function(Object) then
						Tracked = true;
						break;
					end
				end

				ObjectSetTracked(Object, Tracked);
			end
		end
	end
);
```
It makes FPS drop when object count over 1000 even dosent loaded BR (e.g. Nythendra, Return to Karazhan)
I do a dirty hack in GeneralFunctions.lua
```
local GOC = GetObjectCount
function GetObjectCount(BadRotations)
    if BadRotations == "BadRotations" then
        return GOC()
    end
    return 0
end
```

just a suggestion

**Comment by CuteOne** [comment]
Not sure what you are doing with that code.

**Comment by Aleksaas** [comment]
What is happening with FPS problem? By the way I downloaded newest version today to see if the problem is fixed and rotations didn't work, when I attack dummy it says invalid target...
