### ISSUE TITLE
FPS issue

### ISSUE THREAD

**Issue by Reallynigga** [CuteOne/BadRotations#40]
There's a global FPS issue when the rotation is ON.

I drop from ~220 fps to ~20 in raids or suramar city, when there's a high number of ennemies. In combat **and** Out of combat.

Disabling rotation restore full FPS. 

Seems to be the ennemies count frequency or something like that : More ennemies = more drop

(Test as Feral and DH, with High-end pc)

**Comment by CuteOne** [comment]
can you give me a specific location i can go test at? (You mentioned Suramar City, does any point work or is there a certain spot?)

**Comment by Reallynigga** [comment]
Hi,

It's actually dropping at Moon Guard Stronghold in Suramar area. I'll make some screenshots

**Comment by Reallynigga** [comment]
There's FPS in Top middle

Rotation **OFF**
http://img11.hostingpics.net/pics/118724WoWScrnShot020517004806.jpg

Rotation **ON**
http://www.hostingpics.net/viewer.php?id=231595WoWScrnShot020517004816.jpg

**Comment by CuteOne** [comment]
Working on it

**Comment by CuteOne** [comment]
I believe I have made headway but not complete satisfied with it yet.

**Comment by CuteOne** [comment]
Ok hopefully the latest update helps with your FPS, please let me know how it fairs.

**Comment by Reallynigga** [comment]
That's really better, thank you 👍

**Comment by Reallynigga** [comment]
FPS losses are back, I do not know why or how. I met the symptoms again in Karazhan (dungeon).

~250 FPS without, ~30 FPS with. With some shuttering

**Comment by CuteOne** [comment]
Yea I probably have to just abandon my implementation for a different method.

**Comment by Reallynigga** [comment]
I have tryed with Firehack and any FPS losses ! The problem is with EWT.

**Comment by darhanger** [comment]
Confirm! Havent Firehack but some time fps been normal, a few days ago, the problem returned with EWT + BadRotation fps drop to 3-5

**Comment by gaodayihao** [comment]
this the FireHack Issues.In FireHack 2.3.7\Lua\Tracking.lua  line:53.  replace GetObjectCount() in 0 to solve
@Reallynigga

**Comment by Reallynigga** [comment]
@gaodayihao As I said I have this problem only with EWT. 

With FH I have any problem (exception the fact that FireHack is paying).

**Comment by CuteOne** [comment]
Closing due to age
