### ISSUE TITLE
"wise target" lowest doesn't target totems

### ISSUE THREAD

**Issue by edgarskrauklis** [CuteOne/BadRotations#404]
is there some option how to setup that dynamic targeting with wise target at first target totems? (or switch to them if appear any)

**Comment by kuukuukuatchu** [comment]
If there is a boss totem that should be prioritized, it can be added.  If you're asking for PvP, we do not support PvP functions in the live version of BR.

**Comment by edgarskrauklis** [comment]
no, i mean just usual totems in pve. not raids just quests/world pve

**Comment by kuukuukuatchu** [comment]
I don't see anything in dynamic target that would prevent it from targeting a totem if it had lowest health in the area.  If wise target is set to lowest, it should target them from what I can see in the code.

That's not what's happening though?

**Comment by edgarskrauklis** [comment]
don't know - didn't tried yet. but we can close this ticket if you say so. latter if will be any change we can look again at that

**Comment by edgarskrauklis** [comment]
tried on lvl 26 warior. still the same if there is mob with totem then it will auto-target mob. when i click to totem manualy - it switch back to mob.
have dyn.targeting: default, target dynamic target: enabled, hostiles only: disabled, mc targets: enabled, ench time to die: enabled, wise target: lowest, avoid shields: enabled, safe damage check: enabled, dont break ccs: enabled, skull first: enabled, crowd control: enabled

**Comment by kuukuukuatchu** [comment]
Just tested in Atal'Dazar and it targetted boss' reanimation totems just fine.

**Comment by edgarskrauklis** [comment]
seems works good, thank you
