### ISSUE TITLE
Aff Lock Targeting and rotation execution issue

### ISSUE THREAD

**Issue by demonicpeoples** [CuteOne/BadRotations#41]
Not sure if its just limited to affliction lock but after this latest commit the affliction lock rotation doesnt seem to want to target or cast anything after commit 2582. I am not sure what is causing it. If I can get some help debugging this and resolving it, it would be much appreciated.

**Comment by CuteOne** [comment]
Is this still an issue?

**Comment by CuteOne** [comment]
Closing due to no reply
