### ISSUE TITLE
Some requests(Trinkets and requests)

### ISSUE THREAD

**Issue by Subyoz** [CuteOne/BadRotations#43]
1 - Rotation didn't use new legendary trinket.
2 - Is there is posibility to add config for Artifact- usage only with buff\some condition ?

**Comment by kuukuukuatchu** [comment]
What class/spec?  Likely isn't support built in for it would be my first guess.

**Comment by Subyoz** [comment]
elem sham. In Ascendance build under Power of the Maelstrom buff

**Comment by Losar22** [comment]
Fury Warrior, seems to be popping Draught of Souls without battlecry up, even though the trinket only appears during battlecry window rotation.
