### ISSUE TITLE
warior arms: with latest (24.10) versions doing multiple actions at once

### ISSUE THREAD

**Issue by edgarskrauklis** [CuteOne/BadRotations#434]
hi,
i took fresh files on 24.10 - and now my warior doing heroic leap and in midle of leap use heroic throw or charge if available.
i have enabled heroic leap, heroic leap -target, heroic charge (it doesn't have impact, happens the same if disabled) and charge, heoric throw.

**Comment by Druxlolz** [comment]
Hallo.

What talents are using? i made an update that should fix a problem with boundingstride talent.
Also Heroic throw while leaping should also be fixed now.

**Comment by edgarskrauklis** [comment]
thanks, seems this is fixed. only currently doesn't cast "heroic throw" on lvl 26 at all. but doesn't leap and charge at once.

**Comment by kuukuukuatchu** [comment]
Closing issue as resolved.  Please reopen if issue still exists
