### ISSUE TITLE
orc arms warior: racial

### ISSUE THREAD

**Issue by edgarskrauklis** [CuteOne/BadRotations#437]
hi,
is it possible to add that orc racial is triggered at low levels while leveling, with aoe maybe? as currently didn't noticed that it would ever been trigered.

**Comment by Druxlolz** [comment]
Do you have racials checked?

**Comment by edgarskrauklis** [comment]
yes i had enabled racials. about when - would be good at least that it works at all - or to add option that can be trigered asap or on aoe only

**Comment by kuukuukuatchu** [comment]
Added support for normal use of racial if you don't have colossus smash in the last update.  Closing ticket.
