### ISSUE TITLE
BadRotations + EWT?

### ISSUE THREAD

**Issue by highend** [CuteOne/BadRotations#45]
Isn't it possible to use BadRotations in conjunction with Easy WoW Toolbox?

Even when EWT is attached to WoW and running in Backgrounds - Reads/Safe Writes mode and
[x] [No Memory Write] Lua Unloacker is ticked I only get this message in WoW:

```
[BadRotations] Cannot Start... Firehack is not loaded. Please attach Firehack
```

Can anyone post some advice to get this team working?

**Comment by Subyoz** [comment]
coz RTFM
u must use Full Unlock in EWT

**Comment by kuukuukuatchu** [comment]
Solved. Closed.
