### ISSUE TITLE
disc priest routine: how to force heal npc unit?

### ISSUE THREAD

**Issue by edgarskrauklis** [CuteOne/BadRotations#468]
hi,

how with setup can be forced to heal "avatar of Sethraliss"? it doesn't heal it even with special heals marked in healing enging and choosed there T/M/F.

**Comment by LSharpAura** [comment]
Are you setting it as focus, target or mouseover with special heal enabled?  That's what T/M/F stand for.

**Comment by edgarskrauklis** [comment]
yes, i added it to focus. also tried with targeting (t i suppose is for Target)

**Comment by LSharpAura** [comment]
Latest update of my profile should heal Seth now since special heal seems to be buggy. Closing ticket.
