### ISSUE TITLE
CR doesnt use any spells

### ISSUE THREAD

**Issue by Trasher2000** [CuteOne/BadRotations#47]
For some reason my SP doesnt start combat :-/ FH is injected and addon is loaded and enabled but when I click on a training dummy its doing nothing, even when I do the first cast manually :-(
Can I create any kind of logs to provide?

**Comment by CuteOne** [comment]
This could have been done to a recent change I did (which is now restored) also as mentioned I am working on a complete rewrite of the profile.

**Comment by CuteOne** [comment]
Is this still an issue?
