### ISSUE TITLE
SP: Powerword: Shield on CD

### ISSUE THREAD

**Issue by Trasher2000** [CuteOne/BadRotations#48]
Hi
I noticed that whenever I move, the CR casts Powerword: Shield on CD. I didnt find any option to turn it off

**Comment by CuteOne** [comment]
This will likely change as I am working on a rewrite of the profile.

**Comment by bizkut** [comment]
Do you use Body and Soul talent? That's how it works.

**Comment by CuteOne** [comment]
Closed due to no reply.
