### ISSUE TITLE
nil value error

### ISSUE THREAD

**Issue by bizkut** [CuteOne/BadRotations#485]
I got this error when using fengshen holy paladin
219x ...dRotations\System\Engines\HealingEngineFunctions.lua:125: attempt to compare number with nil
...dRotations\System\Engines\HealingEngineFunctions.lua:125: in function `getUnitsToHealAround'
...dRotations\System\Engines\HealingEngineFunctions.lua:51: in function `castWiseAoEHeal'
[string "HolyFengshen.lua"]:815: in function `Cooldowns'
[string "HolyFengshen.lua"]:1224: in function `run'
...aceBadRotations\System\Loader\cCharacter.lua:223: in function `startRotation'
...rfaceBadRotations\System\Loader\cBuilder.lua:684: in function `update'
BadRotations\System\Core.lua:140: in function <BadRotations\System\Core.lua:77>

Locals:
InCombatSkipped

**Comment by kuukuukuatchu** [comment]
Should be fixed with latest push.  Please reopen if still a problem.  Also hi bizkut, nice to see you again haha.
