### ISSUE TITLE
LUA - unlocker by CuteOne

### ISSUE THREAD

**Issue by darhanger** [CuteOne/BadRotations#49]
Hello! I wanted to ask if you have the opportunity to create your LUA - unlocke especially for BadRotations? hat would be well optimized for all, and did not cause any problems like EWT or FireHack

**Comment by CuteOne** [comment]
I have nowhere close to the knowledge I would need to make an unlocker little on one that was as secure as those on offer, plus I would feel awful if I directly lead to the loss of people accounts.

**Comment by d3t4** [comment]
i wont mind if my account gets banned....those who minds are welcomed to pass the opportunity...so plz if you don't mind can you please see to this request and besides it would be learning opportunity.

**Comment by darhanger** [comment]
I understand your morale, but it is a choice for each player. If he chose the path BadRotations + any lua unlocker in any case, can lead to blockage accounts. From myself I can add that everyone uses it at your own risk and if you get banned, or will fall, the whole responsibility on the player. Hands him no twisting, and no one forced to Use rotation. In this you can absolve themselves of all responsibility.

**Comment by kuukuukuatchu** [comment]
Cute does not wish to make an unlocker.  Please use firehack or ewt. Closing issue.
