### ISSUE TITLE
Arms Warrior: "slam issue" standing still

### ISSUE THREAD

**Issue by Claassenx** [CuteOne/BadRotations#492]
Rotation standing still for <6 sec when "Mortal Strike" and "Overpower" is on cd. 
"Slam" is available as filler and could be used instead.

**Comment by Druxlolz** [comment]
How much rage did you have when this happend?

**Comment by Claassenx** [comment]
Around 40-60. It happens randomly where it refuses to "Slam" and waits for Mortal Strike or Overpower.

**Comment by Druxlolz** [comment]
Hello again.

So i just looked over the code and it seems that it will first start using slam on 60 rage or more.
So my new question is the following:

When this thing you speak about happens does it cap rage?
How much hp does the mob have when this happens? 
and what rotation setting are you using? (auto/single/multi)

**Comment by Claassenx** [comment]
Hey,
1. I remember it going to ~60-70 Rage but never was in a situation with full Rage
2. Mob was at ~50-60% hp
3. Auto-Mode

**Comment by Druxlolz** [comment]
Okay i don't think there is anything to worry about it keeps 60 rage since if we enter execute phase we want to be prepared :)
