### ISSUE TITLE
Bug - spamming error

### ISSUE THREAD

**Issue by Subyoz** [CuteOne/BadRotations#50]
With new update - when bot staying in OFF mode and any Unlocker not loaded - bot spaming that Cannost start bla bla bla plz start Firehack.

Older versions dont  have that bug

**Comment by CuteOne** [comment]
That's not a bug

**Comment by Subyoz** [comment]
but why it's happening ?

**Comment by CuteOne** [comment]
People commonly forget to attach FH, its there as a reminder.

**Comment by Subyoz** [comment]
maybe u will add option to disable it ? plz. it's very annoying.

**Comment by CuteOne** [comment]
Do you commonly run with the bot on and no FH, it shouldn't spam with it off

**Comment by Subyoz** [comment]
im always have Bot on in addons(but off in game) but when i need it, im launching FH and puting bot to ON.

**Comment by CuteOne** [comment]
Does it spam when you have the main button off as well?

**Comment by Subyoz** [comment]
yes

**Comment by Subyoz** [comment]
did a fresh install... no errors. U can close topic :)
