### ISSUE TITLE
Elemental shaman multitarget

### ISSUE THREAD

**Issue by Subyoz** [CuteOne/BadRotations#52]
Need to fix rotations. WHile we have 2 targets, bot continue to use Lightning insteed of Chain lightning.

Multi-Target Rotation:

2 Targets

Replace Lightning Bolt with Chain Lightning
Cast Flame Shock both targets with the same considerations as ST
Make these changes and do the single target rotation above.
3 Targets

Cast Liquid Magma Totem if selected
Cast and maintain Flame Shock on all targets
Cast Chain Lightning
Cast Lava Burst only with Lava Surge procs
Cast Earthquake if your Maelstrom is 50 or higher, in place of Earth Shock
4+ Targets

Cast Liquid Magma Totem if selected
Cast Chain Lightning
Cast Earthquake when available

**Comment by CuteOne** [comment]
I updated Elemental has this addressed your issues?

**Comment by Subyoz** [comment]
thx. i`ll test.
