### ISSUE TITLE
Not Sure How To Run

### ISSUE THREAD

**Issue by Ellebora** [CuteOne/BadRotations#56]
How do I run this program? Was recommended by a friend but I see no file I should be running :(

**Comment by CuteOne** [comment]
You install it like a wow addon
Rename extracted folder to just "BadRotations" as GitHub likes to add -master on the end
Load WoW
Attach FH
Ensure BadRotations is in ingame addon list (near bottom)
Load Character and mouseover minimap icon for info to access UI elements.
Join Discord if you need further assistance or just want to hang out with others... https://discord.gg/GkSJVPh
