### ISSUE TITLE
rogue

### ISSUE THREAD

**Issue by BapnB** [CuteOne/BadRotations#57]
assasination and sub rogue has bugs with stealth. can you check it?

ps can i use healing routines in pvp? or its just made for pve?

**Comment by CuteOne** [comment]
They are optimized for pve but there should be nothing preventing pvp use.

**Comment by CuteOne** [comment]
also can you clarify on the stealth issue?

**Comment by BapnB** [comment]
![default](https://cloud.githubusercontent.com/assets/25757064/23069128/4e4e89e2-f537-11e6-8059-452c9e7dd5bc.png)

**Comment by CuteOne** [comment]
panel should have no bearing on whats used or not, my guess its trying to cast a spell that it cant, if you can enable the rotation log and show me that when its messing up that may help.

**Comment by BapnB** [comment]
![default](https://cloud.githubusercontent.com/assets/25757064/23097756/dea8f86c-f64d-11e6-8423-d3ddaf23f5f9.png)
only this
