### ISSUE TITLE
getHPLossPercent

### ISSUE THREAD

**Issue by Sourc** [CuteOne/BadRotations#58]
Sorry if I make a wrong assumption here but I assume the function _getHPLossPercent_ is supposed to return how many percent health was lost in the last _sec_. If so then the function doesn't return the realtime value but rather how much hp was lost since the last time the interval ticked, which it does at the interval provided as an argument to the function.

To calculate the realtime hp lost you would have to, for example, save how much hp the player lost on a set timer (like 1 second) and then in the _getHPLossPercent_ function you would retrieve the _sec_ most recent items from the list and sum them. To keep the list from going on forever you could reset it when combat ends or after one minute, something like that.

At moment I'm lazy and not in the mood of implementing this and so I'll leave it as an issue here instead.

**Comment by Paradokz** [comment]
This will be a great function for more dynamic ways of building the rotations. The AI will be more human like.
