### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by Petetsmisc** [CuteOne/BadRotations#634]
I have downloaded the folder (Badrotations) now the question is, how do I use it?
Is there an executable I have to click on, do I put this folder to my addons folder in wow?
I s there a "Instructions" document for the use of this adddon, at this point I don't have a lua unlocker, do you recommend one?

Thanks,
noob-Pete

**Comment by LSharpAura** [comment]
There's a welcome section on discord that explains how to step it up and you will require either EWT or kfm unlocker as they are the only ones that work with br

**Comment by Petetsmisc** [comment]
Thanks for the reply, what is the discord server ID that I can use? Again
sorry for not knowing all this stuff.

**Comment by CuteOne** [comment]
https://discord.gg/5MejVRp
