### ISSUE TITLE
Reduce the gap between spell

### ISSUE THREAD

**Issue by qj739** [CuteOne/BadRotations#636]
Hi all,
I found that there is a small gap between the casted spell .  
eg ,the GCD = 1.5s , the first spell cast time is start at 0.00s , and the second spell is casted at 1.62s , 1.62-1.5=0.12s , this is the gap.  If I cast the spell manually , the gap is 0 , because there is a spell queue  Mechanism , Can BR modify the engine code to resolve this issue ?
This is not important to healing specialization , but it is very important for DPS. Ff we can solve this issue ,DPS can be improved 5-10% percent.
This is a suggestion. Thank you.

**Comment by qj739** [comment]
In other words , We must cast the second spell  when is first spell is on casting status , but not on it finished

**Comment by CuteOne** [comment]
What spec/profile are you playing?

**Comment by qj739** [comment]
All non-instant cast spec ,such as frozen mage and balance druid has the problem.
I use auto delay , my FPS is 50 above . I set the spell queue window to  200ms , I do not know  the spell gap is related to these parameters.
I checked the code in cast.lua line 331:
 **timersTable[SpellID] <= GetTime() -0.6**
I t seems the cycle is not run every 0.1 second ,but 0.6 sec ?
