### ISSUE TITLE
Elemental shaman aoe with flame shock requests.

### ISSUE THREAD

**Issue by imdasandman** [CuteOne/BadRotations#64]
Rotation is working better since cute ones update but in aoe mode it will multi cast flame shock when you have more than 3 units within 8 yards of prinary target.  Once you have 4 or more it should just be chain lightning spam til we have 50 or more maelstrom than cast earthquake.

Another option that would be nice is if add has less than x amount of hp to ignore using flame shock all together. This would make clearing trash and dealing with adds alot easier.

**Comment by CuteOne** [comment]
This can be done

**Comment by CuteOne** [comment]
This should be implemented
