### ISSUE TITLE
Restoration Shaman

### ISSUE THREAD

**Issue by darhanger** [CuteOne/BadRotations#66]
Restoration Shaman issue. Heals only himself. Maybe need on some custom setings? 

![image](https://cloud.githubusercontent.com/assets/22445395/23215560/885c9466-f91b-11e6-9c07-58303bdc1319.png)

**Comment by darhanger** [comment]
Noup, just heal myself. Maybe need turn on some custom setings? 

![image](https://cloud.githubusercontent.com/assets/22445395/23245301/20fb1d8c-f994-11e6-8e9c-afbbdc3b6bfc.png)

**Comment by SvsGit** [comment]
You need to set Special Heal in Healing Engine menu to heal any unit that not in party/raid with you. I usually set it to T/M/F (target/mouseover/focus).
