### ISSUE TITLE
Feral gets stuck casting wildcharge when in melee range

### ISSUE THREAD

**Issue by ICEE93** [CuteOne/BadRotations#660]
as title, wild charge cant be casted in melee range just like any other charge.

**Comment by CuteOne** [comment]
Hmm that's not right, cast should be accounting for that. I will try to look it over later today.

**Comment by CuteOne** [comment]
I had been running without Wild Charge enabled, but I turned it on and did some world quests with no issue.

**Comment by ICEE93** [comment]
i still have this issue, it does seem abit random though... at times i can run a full raid with no issue, at some point it will just get stuck spamming, i dont really know how to reproduce it at this time

**Comment by CuteOne** [comment]
In the mean time, it is disable-able and there is good argument to be made for manual use.

**Comment by ICEE93** [comment]
yea, thats what i do atm, i usually run with disabled movement spellcasts if possible, this was noticed during my legacy soloing runs and reproduced a second time yesterday after the EU reset, dont know what triggers it though.

**Comment by CuteOne** [comment]
If you have bugsack, it may be helpful if it generates an error.

**Comment by ICEE93** [comment]
it does not throw an error unfortunatley, i just see the visual for the buttonpress repeatedly on wild charge and the BR toggle icon sticks to wild charge, ill try to pin it down further during the evening

**Comment by CuteOne** [comment]
I'll toss some debug prints and see if I get anything when I have a chance.

**Comment by kuukuukuatchu** [comment]
Current check is 8+ yards, up to 30.  Ability itself says 5-30 yard so should be working fine in melee range actually. Unless of course Blizzard lies... but they never do that....

**Comment by kuukuukuatchu** [comment]
Closing due to age and inability to replicate issue.  Please reopen if still any issue.
