### ISSUE TITLE
#arms warrior - Hamstring

### ISSUE THREAD

**Issue by edgarskrauklis** [CuteOne/BadRotations#681]
hi,
is it possible to add some functionality -  that if secleted "general->hamstring" then execute skill if target increase distance from player?
currently  seems that it doesn't do anything.

thanks.

Edgars

**Comment by LSharpAura** [comment]
Why would something be moving away from you? Mobs generally just fight till they're dead.  Request doesn't make a lot of sense to me personally.

**Comment by ICEE93** [comment]
Nothing pvp related will be added to BadRotations.

**Comment by edgarskrauklis** [comment]
not pvp - just some mobs moving away when close to death. mostly caster type

**Comment by kuukuukuatchu** [comment]
Closing due to recent updates in BR making this question moot.
