### ISSUE TITLE
Die By The Sword isn't trigered

### ISSUE THREAD

**Issue by edgarskrauklis** [CuteOne/BadRotations#684]
Hi,

            br.ui:createSpinner(section, "Die by the Sword",  60,  0,  100,  5,  "|cffFFBB00Health Percentage to use at.")

should be replace with:

            br.ui:createSpinner(section, "Die By The Sword",  60,  0,  100,  5,  "|cffFFBB00Health Percentage to use at.")

otherwise skill isn't trigered due case sensitive mismatch in getOptionValue.

```
if isChecked("Die By The Sword") and cast.able.dieByTheSword() and inCombat and php <= getOptionValue("Die By The Sword") then
                    if cast.dieByTheSword() then return end
                end
```

Edgars

**Comment by kuukuukuatchu** [comment]
Should be fixed now

**Comment by edgarskrauklis** [comment]
thanks
