### ISSUE TITLE
Again. Bot spaming.

### ISSUE THREAD

**Issue by Subyoz** [CuteOne/BadRotations#69]
![wowscrnshot_022317_121107](https://cloud.githubusercontent.com/assets/25648941/23254423/ba09c736-f9c0-11e6-821f-fa049bea2bd5.jpg)
as u can see - rotation disabled

**Comment by CuteOne** [comment]
That is by design, some people were having issues and it was because they forgot to enable FH so I added that periodic warning.

**Comment by Subyoz** [comment]
it's annoying =\ how i can disable it ?=)

**Comment by CuteOne** [comment]
There is now an option to configure it with the latest update

**Comment by Subyoz** [comment]
ty.
