### ISSUE TITLE
lua error and more

### ISSUE THREAD

**Issue by Subyoz** [CuteOne/BadRotations#70]
Again me :d 
after last update

![wowscrnshot_022317_130101](https://cloud.githubusercontent.com/assets/25648941/23256380/d8a44ed0-f9c7-11e6-9984-097f21d4bc87.jpg)

and also when im enabling rotation - window with shortcuts(on\off, cds,defence and etc) dissapear

**Comment by CuteOne** [comment]
Still an issue with the latest update? 1hr ago as of this post

**Comment by Subyoz** [comment]
yes it came with latest update (i did update after prev. topic)

**Comment by SvsGit** [comment]
Fixed
