### ISSUE TITLE
Restoration Shaman

### ISSUE THREAD

**Issue by darhanger** [CuteOne/BadRotations#71]
5 ppl rotation not working. just heal myself. Im no sure but in raid all fine

![image](https://cloud.githubusercontent.com/assets/22445395/23259692/f76746ec-f9d6-11e6-978e-9cc1d9798989.png)

**Comment by CuteOne** [comment]
Try the latest update

**Comment by darhanger** [comment]
When turn on rotation

Message: ...s\BadRotations\System\Engines\HealingEngineFrame.lua:3: attempt to index field 'healingDebugFrame' (a nil value)
Time: 02/24/17 08:07:49
Count: 127
Stack: ...s\BadRotations\System\Engines\HealingEngineFrame.lua:3: in function `pulseNovaDebug'
...AddOns\BadRotations\System\Engines\HealingEngine.lua:497: in function `Update'
Interface\AddOns\BadRotations\System\Core.lua:131: in function <Interface\AddOns\BadRotations\System\Core.lua:79>

Locals: (*temporary) = nil
(*temporary) = nil
(*temporary) = false
(*temporary) = "Healing DebugCheck"
(*temporary) = "Check"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'healingDebugFrame' (a nil value)"

**Comment by darhanger** [comment]
Debug off 

![image](https://cloud.githubusercontent.com/assets/22445395/23292698/2c8ea4b2-fa6a-11e6-8617-25aa04b0db4a.png)

**Comment by SvsGit** [comment]
EWT is not supported
