### ISSUE TITLE
Empower/Hungering rune weapon bug

### ISSUE THREAD

**Issue by zitnik1ng** [CuteOne/BadRotations#73]
hello, basrotations never use Empower/Hungering rune weapon in combat
edit : Auto detect boss dont works,i have check all cooldowns, If not it never burst
best regards

**Comment by CuteOne** [comment]
Tested against Garrison dummy, CDs and Empower/Hungering Rune Weapon worked.

**Comment by CuteOne** [comment]
Closed due to no reply
