### ISSUE TITLE
Druid Resto  !!!!

### ISSUE THREAD

**Issue by Chifo77** [CuteOne/BadRotations#74]
Last week I use the rotation and works perfect, but I try to use it today and ddnt work well, some time it never star healing just change from's, dut know if im doing smthing wrong....

Also, what talents do you recomend for the rotation!!!!

Tks and Good Work

**Comment by SvsGit** [comment]
Rotation is thoroughly tested before publishing. So either youre not updated or doing something wrong.
Recommended biulds and settings pinned in #druid channel in our Discord: https://discord.gg/GkSJVPh
