### ISSUE TITLE
BR does not open main UI

### ISSUE THREAD

**Issue by agantar** [CuteOne/BadRotations#750]
After I am in the game and press the fire button it does nothing, also tried by typing ```/br ui main``` and I just hear the interface clicking, nothing else.

Otherwise, it says it's loaded and I see the ON/OFF button

What could it be?

**Comment by kuukuukuatchu** [comment]
If you only see on/off button then it sounds like your unlocker is not active.

**Comment by agantar** [comment]
I see also the fire next to the minimap but when I click it does not do anything...
I also see the message as if the BR is loaded.

**Comment by bizkut** [comment]
You need to turn on the rotation to open the main UI. toggle `/br`

**Comment by kuukuukuatchu** [comment]
Closing due to solution being provided  Please reopen if problem persists.
