### ISSUE TITLE
Survival Hunter dummy issue

### ISSUE THREAD

**Issue by powerpanda98** [CuteOne/BadRotations#77]
Hi, I love the rotations in general, but there's a problem with survival (other than the fact that it's unfinished). Whenever I try to test the DPS on a ST dummy, (any dummy) the rotation never uses fury of the eagle. Atm I do 320k out of 366k (sim), without using fury of the eagle, but I'm not good enough at the spec to figure out why it's 46k behind, except of course some of the damage is simply the artifact ability never being used. When I sim my char, it shows (http://prntscr.com/ee89wr) fury of the eagle is 5% of my damage. Other than this, as I said, I'm not familiar enough with the spec to see the flaws, but I would love for it to hit 100% soon :). Thanks for your amazing work.

**Comment by CuteOne** [comment]
Is this still an issue?

**Comment by kuukuukuatchu** [comment]
Closed due to lack of response
