### ISSUE TITLE
7.0.3 not fully supported

### ISSUE THREAD

**Issue by d3t4** [CuteOne/BadRotations#78]
I know that you have been creating this rotation for updated version but could u make it so that it support 7.0.3....i guess some codes are not supported which i have to edit everytime to make it work so if u could do that it would be perfection 👍

**Comment by CuteOne** [comment]
My hands are full with Live as it is, I don't have the time to adjust for every change for prior patches....that said one possible middle ground for you would be to explore the commit history and try to find the last commit in 7.0.3, in theory that should work.

**Comment by d3t4** [comment]
no worries...yeah tried that but some new rotations malfunctions....and i seem to find error with mainButton in ui...is it just me?

**Comment by CuteOne** [comment]
I am dealing with some strange/random errors recently, still investigating

**Comment by CuteOne** [comment]
These should be resolved, closing
