### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by Inspirelol** [CuteOne/BadRotations#783]
I averaged over 200fps,  I downloaded the updated addon folder today and now my fps is sitting at 8-10.

**Comment by Inspirelol** [comment]
I swapped back to my old BadRotations folder and the FPS issues are gone.

Running Holy Paladin.

**Comment by Vilt-Coding** [comment]
Any idea when this started happening?

**Comment by Inspirelol** [comment]
When I downloaded the updated addon folder.  My previous addon was downloaded on 7/20/2019

**Comment by Inspirelol** [comment]
The issue is still relevant.

**Comment by CuteOne** [comment]
I have not heard anything recently...only thing that was relevent was an EWT issue.
