### ISSUE TITLE
Pause on Legion 

### ISSUE THREAD

**Issue by zekaey** [CuteOne/BadRotations#788]
So I spent all night trying to implement pause script from BfA. Can you please implement it to your 1.16 latest legion Tag ? 👍

This is a follow up to my previous post: https://github.com/CuteOne/BadRotations/issues/222

But it seems like you only implemented it when BfA came out -_-

**Comment by CuteOne** [comment]
And sadly we only support Live, good news is you wont loose your change as there are no new updates to the last legion tag.

**Comment by zekaey** [comment]
Thnx :)
