### ISSUE TITLE
Little change and will be super OP!

### ISSUE THREAD

**Issue by Zhorinwow** [CuteOne/BadRotations#796]
Hello everyone! The first thing is to thank for the great work you do! My suggestion is about the feral druid. The macro is great but it only has a small bug. When the target has all the dots and has five combo points, it takes a long time to use Ferocious Bite. It costs 25 energy but does not use it until it reaches practically 50 or 60 and much damage is lost, could they modify this? The profile is from the cuteone. Thank you very much in advance.

**Comment by CuteOne** [comment]
Ferocious Bite does extra damage upto 25 extra energy.
![image](https://user-images.githubusercontent.com/5498251/64174290-f40bbd80-ce26-11e9-8ffc-99c9e230dd16.png)

**Comment by CuteOne** [comment]
Closing due to no response.
