### ISSUE TITLE
UnitDebuffID with TimeLeft

### ISSUE THREAD

**Issue by zekaey** [CuteOne/BadRotations#799]
Any way of having two functions in one?
**For example having:** 
if UnitDebuffID("target", 123, 3, "player") **instead of current:**
UnitDebuffID("target", 123, "player") and getDebuffRemain("target", 123) < 3

Initially I thought that the **isDeBuffed**(UnitID, DebuffID, TimeLeft, Filter)  can do it. However it doesn't work in BfA.

**Comment by LSharpAura** [comment]
Why do you need to do UnitDebuffID? Just use getDebuffRemain if you need the remaining time?

**Comment by CuteOne** [comment]
remain will return 0 if it doesn't exist

**Comment by kuukuukuatchu** [comment]
Closing due to solution provided. Please reopen in issue persists.
