### ISSUE TITLE
monk healer error

### ISSUE THREAD

**Issue by leaderquebec** [CuteOne/BadRotations#80]
when i load fh got this error

ID: 1
Error occured in: Global
Count: 1
Message: ...AddOns\BadRotations\System\Libs\!LibDraw\LibDraw.lua line 10:
   attempt to call upvalue 'WorldToScreen_Original' (a nil value)
Debug:
   ...AddOns\BadRotations\System\Libs\!LibDraw\LibDraw.lua:10:
      ...AddOns\BadRotations\System\Libs\!LibDraw\LibDraw.lua:9
   ...AddOns\BadRotations\System\Libs\!LibDraw\LibDraw.lua:73: Line()
   ...dRotations\System\Engines\HealingEngineFunctions.lua:238: getUnitsInRect()
   ...ions\Rotations\Monk\Mistweaver\MistweaverLyLoLoq.lua:456: actionList_AOEHealing()
   ...ions\Rotations\Monk\Mistweaver\MistweaverLyLoLoq.lua:573: run()
   ...terface\AddOns\BadRotations\Rotations\cCharacter.lua:293: startRotation()
   BadRotations\Rotations\cBuilder.lua:381: update()
   BadRotations\System\Core.lua:193:
      BadRotations\System\Core.lua:82

/reload fix this !

**Comment by kuukuukuatchu** [comment]
Problem solved. Closing
