### ISSUE TITLE
Shadow priest sliders not working

### ISSUE THREAD

**Issue by Cyberking07** [CuteOne/BadRotations#82]
762x ...Rotations\Rotations\Priest\Shadow\ShadowCpoworks.lua:675: attempt to compare number with nil
...Rotations\Rotations\Priest\Shadow\ShadowCpoworks.lua:675: in function `actionList_VoidForm'
...Rotations\Rotations\Priest\Shadow\ShadowCpoworks.lua:845: in function `run'
BadRotations\Rotations\cCharacter.lua:293: in function `startRotation'
BadRotations\Rotations\cBuilder.lua:381: in function `update'
BadRotations\System\Core.lua:193: in function <BadRotations\System\Core.lua:82>

Locals:

**Comment by CuteOne** [comment]
Should be fixed now

**Comment by CuteOne** [comment]
Closed due to no reply
