### ISSUE TITLE
BM Aspect of the Wild

### ISSUE THREAD

**Issue by ubunto0101234** [CuteOne/BadRotations#83]
For some reason Aspect of the Wild is never used in the rotation, even tho it's ticked. Really, other than that the damage is quite insane at times?

Concusssive Shot - would be great is this could be a constant cast option on current target.
Auto rez pet - would be great.
Traps - I'm sure would be really difficult to implement but would be great if there was some kinda predictive cast option.

I know BM is sporadic update but would be awesome if tweaked.

**Comment by CuteOne** [comment]
Is this still an issue?

**Comment by ubunto0101234** [comment]
Hi, yeah still having to cast AOW manually - haven't ever seen it trigger by itself.

**Comment by kuukuukuatchu** [comment]
What apl are you using? AotW works fine with the Kuu apl.

**Comment by ubunto0101234** [comment]
Sorry - been working overseas! I was using Simc which doesn't work, but yes, it works with Kuu. Could you possibly take a look at BM Trinkets? No matter what option is ticked (1,2 or both) the trinkets don't fire off, either in Simc or Kuu. I tried taking the trinkets code from MM Hunter but still didn't work. Other than that - I think the rotation is different class - awesome job.

**Comment by ubunto0101234** [comment]
Just a quick update to stop me having to do it manually after every update....it doesnt work in SimC because its not been added to SimC - just needs a copy and paste from from Kuu and all good.

**Comment by kuukuukuatchu** [comment]
Has been done and issue is resolved.  Closing.
