### ISSUE TITLE
Fury Warrior won't DPS with multiple mobs attacking

### ISSUE THREAD

**Issue by oreganobag** [CuteOne/BadRotations#857]
Low level play. I'm guessing there is an AOE that wants to go off but doesn't have a level check on it since AOE isn't unlocked until whirlwind at level 40.

**Comment by Pangloo** [comment]
Yeah that's exactly what it is, I can add a bypass for aoe with expert mobile coding abilities!!

**Comment by oreganobag** [comment]
Bump?
