### ISSUE TITLE
LUA-error when character dies and is in ghost-form.

### ISSUE THREAD

**Issue by adde88** [CuteOne/BadRotations#87]
This happens when i die, and walk around in ghost-form.
As i git pull your repo. several times a day i thought it could be wise to report it.
It also started happening today, and i've never had this lua-error before.

```
382x ...faceBadRotations\System\GeneralFunctions.lua:850: Usage: UnitIsDeadOrGhost("unit")
[C]: in function `UnitIsDeadOrGhost'
...faceBadRotations\System\GeneralFunctions.lua:850: in function `castQueue'
BadRotations\System\Core.lua:149: in function <BadRotations\System\Core.lua:82>

Locals:
(*temporary) = nil
```

**Comment by CuteOne** [comment]
Is this still an issue?

**Comment by adde88** [comment]
No, i haven't experienced it in the latest builds. I'll just close it. 
Thanks! :)
