### ISSUE TITLE
Feral (and possible others) "Auto" rotation always uses AoE rotation in every situation.

### ISSUE THREAD

**Issue by Jokelass** [CuteOne/BadRotations#89]
Whilst using "Auto" instead of "Single" or "AoE" the rotation will always use the AoE rotation (Using thrash on single target) even when there's no critters or anything that could be considered a NPC within sight. 

Only a minor annoyance as it works if you manually swap between single and aoe rotation but it reduces reaction time on bosses and similar stuff as you have to swap the rotation manually once you need AoE.

**Comment by CuteOne** [comment]
There is logic to use thrash in ST...
thrash_cat,cycle_targets=1,if=remains<=duration*0.3&(spell_targets.swipe_cat>=2|(buff.clearcasting.up&buff.bloodtalons.down))

This will use thrash on CC procs when there is not a bloodtalon buff and its lower priority than rake/rip/sr

**Comment by kuukuukuatchu** [comment]
Closing as no response in a month so assuming issue resolved.
