### ISSUE TITLE
Buffs are not recognised in time.

### ISSUE THREAD

**Issue by nevaer** [CuteOne/BadRotations#914]
Noticed it on my Balance Druid, double casts certaint spells. Probably i will add a little delay somehow.
Here is a simple rotation, you can test with it:
`
    -- Action List - Combat
    actionList.Combat = function()
        --if UnitIsEnemy("player", "target") and getFacing("player","target") then
            --if GetUnitExists("target") and not UnitIsDeadOrGhost("target") then
                if cast.able.starsurge() and ((buff.solarEmpowerment.stack() < 3 and buff.lunarEmpowerment.stack() < 3) or br.player.power.astralPower.amount() > 90) then
                    if cast.starsurge() then
                        br.addonDebug("Casting Starsurge")
                        return true
                    end
                end
                if cast.able.solarWrath() and buff.solarEmpowerment.exists() then
                    if cast.solarWrath("target") then
                        br.addonDebug("Casting Solar Wrath Target with Empo")
                        return true
                    end
                end
                if cast.able.lunarStrike() and buff.lunarEmpowerment.exists() then
                    if cast.lunarStrike("target") then
                        br.addonDebug("Casting Lunar Strike Target with Empo")
                        return true
                    end
                end
                if cast.able.lunarStrike() and getNumEnemies("target", 8) >= 2 then
                    if cast.lunarStrike("target") then
                        br.addonDebug("Casting Lunar Strike Target")
                        return true
                    end
                end
                if cast.able.solarWrath() then
                    if cast.solarWrath("target") then
                        br.addonDebug("Casting Solar Wrath Target")
                        return true
                    end
                end
            --end
        --end
    end -- End Action List - Combat
`

**Comment by Laksmack** [comment]
typically comes down to the update rate you are using.  Try fiddle with that - or come talk to us on the discord so we can figure it out
