### ISSUE TITLE
Survival Hunter Not doing anything at low level

### ISSUE THREAD

**Issue by oreganobag** [CuteOne/BadRotations#919]
Just testing the rotations on a new hunter. Survival doesn't perform any actions at low level. I think it's probably trying to cast abilities above the level of the character. Needs some level checks for skills, maybe?

**Comment by CuteOne** [comment]
Can you provide more info, like what level you are, any errors from bugsack (if installed), anything else you think would be helpful.

**Comment by oreganobag** [comment]
Simply leveling up a new hunter, so tried it at level 10. I'm level 18 now, using the Beast Master rotation and have no issues with it working very well, but switching to Survival, it doesn't do anything. 

It looks like its able to use the pet abilities (Bite/Growl/Dash) but that's all. Cast Debug shows it just using pet abilities, but not even attempting to use Raptor Strike which is mainly what you would be using at low level.

**Comment by CuteOne** [comment]
I'll try to make a new survival hunter and see what's up.

**Comment by oreganobag** [comment]
A few more levels and it looks like it has fixed itself. It could possibly be the type of pet you have, too.

**Comment by CuteOne** [comment]
What did you roll as? Or what pet were you using.

**Comment by CuteOne** [comment]
Set opener to never in profile options, it will work then until i push a fix.

**Comment by CuteOne** [comment]
Fix has now been pushed, closing as you are past the level where you were having issues but if you roll Survival again it should be fine.
