### ISSUE TITLE
Healing Rain - 5Man dungeon 

### ISSUE THREAD

**Issue by Druxlolz** [CuteOne/BadRotations#94]
Hello i just want to let you know that Healing Rain sometimes is an issue cuz 
when i'm doing a dungeon and people get low on hp lets say:    3/5 Party Members is 35% hp it would then cast Healing Rain if it's up instead of hammering healing surge or riptide i had to disable it while running dungeon as it way to high prio it would probably make a healing rain on targets with 10% hp as well and then start healing them after healing rain is casted. 

Seems like artifact weapon as resto Shaman  has an aoe ability that gives us 10% health and good amount of healing, this ability can be casted to 40yrd range but it seems like it will cast it on myself every time no matter the situation.  
The name of the ability btw is : Gift of the Queen.

Here is a suggestion. 
Would be awesome to have a option for "Unleash Life" to only use it with chain heal, why? because chain heal is way stronger than any other direct heal we got and if you have legendary ring for shaman healer its even stronger and combined with Unleash Life its op, this is only for raids may be useful other places to but it will for sure get used in raid, as we would be healing surge / healing wave to heal tanks up anyways.

**Comment by SvsGit** [comment]
Adjusted Healing Rain priority and added manual cast key. Please update, test and report back. Thank you.

**Comment by SvsGit** [comment]
Gift of the Queen heals up to six injured allies within 12 yards from player thats why it casted on self. I also have Focuser of Jonat, the Elder ring and Unleach Life + Chain Heal combo make sence. Definitely will implement it. Please come to our Discord at https://discord.gg/GkSJVPhs owe can have a chat.

**Comment by SvsGit** [comment]
Focuser of Jonat, the Elder legenadary ring support added

**Comment by Druxlolz** [comment]
Damn that was fast m8, thx so much for awesome support, i have tested the healing rain prio seems good right now will definitely check out the chain heal build to! :)

**Comment by Druxlolz** [comment]
Hello again :)

Focuser of Jonat, the Elder legenadary ring support added

Can you make a check before casting Chain heal on 5 stacks? it seems to cast chain heal while only 1 target is missing health.
