### ISSUE TITLE
Toggle macros dont work

### ISSUE THREAD

**Issue by mykam** [CuteOne/BadRotations#96]
Hi, since i use BR i used macros to switch between singletarget/auto, cooldowns on/off.
my br was out of date several weeks i guess so i updated it today, since then none of my macros work anymore.

im just using the standart lines from /br help like "/br toggle cooldown 2"

**Comment by CuteOne** [comment]
use /br toggle Cooldown 2

**Comment by kuukuukuatchu** [comment]
Closing as issue appears resolved as no further communication in almost a month
