### ISSUE TITLE
Healer Engine - Debuff healing (Raid)

### ISSUE THREAD

**Issue by Druxlolz** [CuteOne/BadRotations#99]
Hello.

I was wondering if it was possible to somehow make the bot heal targets that has debuff "Time Release"
http://www.wowhead.com/spell=206609/time-release

The problem is sometimes when i fight Chronomatic Anomaly(Night Hold) and raid is fully healed the bot will just stand and do nothing while this debuffs are active on a few people would be nice if healer engine could be able to detect this debuff and heal the targets till the debuff expires or get healed away.

**Comment by kuukuukuatchu** [comment]
It already does this. Tested in lfr raid on Tuesday on my MW.  Unless the id is different where you are seeing it, the HE will assume the target is 30% lower hp than it is until the debuff goes away.
